# translation of anaconda.balochi.po to Balochi
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Mostafa Daneshvar <mostafa@daneshvar.org.uk>, 2008.
msgid ""
msgstr ""
"Project-Id-Version: anaconda.balochi\n"
"Report-Msgid-Bugs-To: anaconda-devel-list@redhat.com\n"
"POT-Creation-Date: 2010-10-19 17:55-0700\n"
"PO-Revision-Date: 2008-03-13 22:52+0330\n"
"Last-Translator: Mostafa Daneshvar <mostafa@daneshvar.org.uk>\n"
"Language-Team: Balochi <fedora-trans-bal@redhat.com>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"

#: anaconda:313
msgid "Press <enter> for a shell"
msgstr "په یک شل <enter> بجنیت"

#: anaconda:336
msgid "Not enough RAM"
msgstr ""

#: anaconda:337
msgid ""
" Try the text mode installer by running:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" from a root terminal."
msgstr ""

#: anaconda:340
#, fuzzy
msgid " Starting text mode."
msgstr "متغیران پیش دارگی تنظیم نهتن. حالت متنی شروع بیگنت!"

#: anaconda:364 pyanaconda/rescue.py:353 pyanaconda/rescue.py:379
#: pyanaconda/rescue.py:392 pyanaconda/rescue.py:475 pyanaconda/rescue.py:488
#: pyanaconda/rescue.py:499 pyanaconda/text.py:534 loader/windows.h:31
#: loader/cdinstall.c:229 loader/cdinstall.c:233 loader/cdinstall.c:249
#: loader/cdinstall.c:252 loader/cdinstall.c:428 loader/cdinstall.c:432
#: loader/cdinstall.c:505 loader/dirbrowser.c:129 loader/driverdisk.c:228
#: loader/driverdisk.c:408 loader/driverdisk.c:440 loader/driverdisk.c:471
#: loader/driverdisk.c:506 loader/driverdisk.c:522 loader/driverdisk.c:534
#: loader/driverdisk.c:542 loader/driverdisk.c:709 loader/driverdisk.c:748
#: loader/driverselect.c:79 loader/driverselect.c:179 loader/hdinstall.c:115
#: loader/hdinstall.c:266 loader/hdinstall.c:325 loader/hdinstall.c:360
#: loader/hdinstall.c:440 loader/hdinstall.c:483 loader/hdinstall.c:496
#: loader/kbd.c:119 loader/kickstart.c:135 loader/kickstart.c:145
#: loader/kickstart.c:187 loader/kickstart.c:192 loader/kickstart.c:299
#: loader/kickstart.c:339 loader/kickstart.c:355 loader/kickstart.c:382
#: loader/kickstart.c:571 loader/lang.c:114 loader/lang.c:373
#: loader/loader.c:433 loader/loader.c:469 loader/loader.c:509
#: loader/loader.c:527 loader/loader.c:544 loader/loader.c:581
#: loader/loader.c:1212 loader/loader.c:1399 loader/mediacheck.c:47
#: loader/mediacheck.c:86 loader/mediacheck.c:93 loader/mediacheck.c:97
#: loader/mediacheck.c:106 loader/method.c:286 loader/method.c:360
#: loader/net.c:621 loader/net.c:1001 loader/net.c:1654 loader/net.c:1675
#: loader/net.c:1981 loader/net.c:2000 loader/net.c:2012
#: loader/nfsinstall.c:116 loader/nfsinstall.c:309 loader/nfsinstall.c:326
#: loader/nfsinstall.c:414 loader/urlinstall.c:137 loader/urlinstall.c:159
#: loader/urlinstall.c:221 loader/urlinstall.c:374 loader/urlinstall.c:385
#: loader/urlinstall.c:392 loader/urls.c:269 loader/urls.c:340
#: loader/urls.c:346 loader/urls.c:355 pyanaconda/textw/constants_text.py:44
msgid "OK"
msgstr "هوبنت"

#: anaconda:727
msgid "Would you like to use VNC?"
msgstr ""

#: anaconda:728
msgid ""
"Text mode provides a limited set of installation options.  It does not allow "
"you to specify your own partitioning layout or package selections.  Would "
"you like to use VNC mode instead?"
msgstr ""

#: anaconda:754
#, fuzzy
msgid "Graphical installation is not available. Starting text mode."
msgstr "وصل بوگ گرافیگی موجود نهنت... متنی حالت شروع بیگنت."

#: anaconda:762
#, fuzzy
msgid "DISPLAY variable not set. Starting text mode."
msgstr "متغیران پیش دارگی تنظیم نهتن. حالت متنی شروع بیگنت!"

#: pyanaconda/backend.py:135
#, python-format
msgid "Upgrading %s\n"
msgstr ""

#: pyanaconda/backend.py:137
#, python-format
msgid "Installing %s\n"
msgstr ""

#: pyanaconda/backend.py:150
msgid "Copying File"
msgstr ""

#: pyanaconda/backend.py:151
msgid "Transferring install image to hard drive"
msgstr ""

#: pyanaconda/backend.py:161
msgid ""
"An error occurred transferring the install image to your hard drive.  This "
"is often cause by damaged or low quality media."
msgstr ""

#: pyanaconda/backend.py:165
msgid ""
"An error occurred transferring the install image to your hard drive. You are "
"probably out of disk space."
msgstr ""

#: pyanaconda/backend.py:169 pyanaconda/image.py:286 pyanaconda/livecd.py:198
#: pyanaconda/livecd.py:440 pyanaconda/partIntfHelpers.py:233
#: pyanaconda/text.py:355 pyanaconda/text.py:359 pyanaconda/yuminstall.py:466
#: pyanaconda/yuminstall.py:838 pyanaconda/yuminstall.py:956
#: pyanaconda/yuminstall.py:961 pyanaconda/yuminstall.py:1225
#: pyanaconda/yuminstall.py:1285 pyanaconda/yuminstall.py:1476
#: pyanaconda/yuminstall.py:1498 pyanaconda/iw/advanced_storage.py:86
#: pyanaconda/iw/advanced_storage.py:96 pyanaconda/iw/advanced_storage.py:170
#: pyanaconda/iw/advanced_storage.py:173 pyanaconda/iw/advanced_storage.py:201
#: pyanaconda/iw/autopart_type.py:95 pyanaconda/iw/cleardisks_gui.py:44
#: pyanaconda/iw/cleardisks_gui.py:54 pyanaconda/iw/filter_gui.py:431
#: pyanaconda/iw/osbootwidget.py:211 pyanaconda/iw/osbootwidget.py:220
#: pyanaconda/iw/raid_dialog_gui.py:223 pyanaconda/iw/task_gui.py:54
#: pyanaconda/iw/task_gui.py:152 pyanaconda/iw/task_gui.py:305
#: pyanaconda/iw/task_gui.py:469 loader/windows.h:31 loader/cdinstall.c:229
#: loader/cdinstall.c:505 loader/driverdisk.c:228 loader/driverdisk.c:471
#: loader/driverdisk.c:506 loader/driverdisk.c:534 loader/driverdisk.c:542
#: loader/driverdisk.c:609 loader/hdinstall.c:115 loader/hdinstall.c:325
#: loader/hdinstall.c:440 loader/hdinstall.c:483 loader/hdinstall.c:496
#: loader/kickstart.c:299 loader/lang.c:114 loader/loader.c:433
#: loader/loader.c:544 loader/loader.c:1212 loader/mediacheck.c:47
#: loader/mediacheck.c:86 loader/mediacheck.c:93 loader/mediacheck.c:97
#: loader/method.c:286 loader/method.c:360 loader/nfsinstall.c:309
#: loader/nfsinstall.c:326 loader/urlinstall.c:137 loader/urlinstall.c:159
#: loader/urlinstall.c:221 loader/urls.c:340 loader/urls.c:346
#: loader/urls.c:355 pyanaconda/storage/__init__.py:230
#: pyanaconda/storage/__init__.py:1818 pyanaconda/storage/__init__.py:1905
#: pyanaconda/storage/zfcp.py:375 pyanaconda/textw/upgrade_text.py:181
#: pyanaconda/textw/upgrade_text.py:188
msgid "Error"
msgstr ""

#: pyanaconda/bootloader.py:55 pyanaconda/bootloader.py:221
#: pyanaconda/bootloader.py:227 pyanaconda/gui.py:1081 pyanaconda/image.py:80
#: pyanaconda/installinterfacebase.py:51 pyanaconda/installinterfacebase.py:82
#: pyanaconda/installinterfacebase.py:142 pyanaconda/packages.py:314
#: pyanaconda/text.py:411 pyanaconda/yuminstall.py:1454
#: pyanaconda/yuminstall.py:1662 pyanaconda/yuminstall.py:1697
#: pyanaconda/iw/blpasswidget.py:148 pyanaconda/iw/upgrade_swap_gui.py:190
#: pyanaconda/iw/upgrade_swap_gui.py:198 pyanaconda/iw/upgrade_swap_gui.py:205
#: pyanaconda/textw/upgrade_text.py:193
msgid "Warning"
msgstr ""

#: pyanaconda/bootloader.py:56
msgid ""
"Filesystems have already been activated.  You cannot go back past this "
"point.\n"
"\n"
"Would you like to continue with the installation?"
msgstr ""

#: pyanaconda/bootloader.py:60 pyanaconda/gui.py:1104 pyanaconda/gui.py:1141
#: pyanaconda/gui.py:1342 pyanaconda/image.py:89 pyanaconda/kickstart.py:156
#: pyanaconda/livecd.py:205 pyanaconda/livecd.py:447
#: pyanaconda/packages.py:131 pyanaconda/upgrade.py:58
#: pyanaconda/upgrade.py:98 pyanaconda/upgrade.py:254
#: pyanaconda/yuminstall.py:257 pyanaconda/yuminstall.py:756
#: pyanaconda/yuminstall.py:958 pyanaconda/yuminstall.py:963
#: pyanaconda/yuminstall.py:1043 pyanaconda/yuminstall.py:1049
#: pyanaconda/yuminstall.py:1204 pyanaconda/yuminstall.py:1221
#: pyanaconda/yuminstall.py:1275 pyanaconda/yuminstall.py:1463
#: pyanaconda/yuminstall.py:1482 pyanaconda/yuminstall.py:1505
#: pyanaconda/storage/__init__.py:114 pyanaconda/storage/__init__.py:123
#: pyanaconda/storage/__init__.py:234 pyanaconda/storage/__init__.py:1999
msgid "_Exit installer"
msgstr ""

#: pyanaconda/bootloader.py:60 pyanaconda/image.py:90 pyanaconda/image.py:249
#: pyanaconda/kickstart.py:1383 pyanaconda/kickstart.py:1422
#: pyanaconda/upgrade.py:58 pyanaconda/upgrade.py:98
#: pyanaconda/yuminstall.py:1280 pyanaconda/yuminstall.py:1464
#: pyanaconda/iw/partition_gui.py:1599 pyanaconda/storage/__init__.py:2000
msgid "_Continue"
msgstr ""

#: pyanaconda/bootloader.py:158
msgid "Bootloader"
msgstr ""

#: pyanaconda/bootloader.py:158
msgid "Installing bootloader."
msgstr ""

#: pyanaconda/bootloader.py:222
msgid ""
"There was an error installing the bootloader.  The system may not be "
"bootable."
msgstr ""

#: pyanaconda/bootloader.py:228
msgid ""
"No kernel packages were installed on the system.  Bootloader configuration "
"will not be changed."
msgstr ""

#: pyanaconda/cmdline.py:56
msgid "Completed"
msgstr ""

#: pyanaconda/cmdline.py:64
msgid "In progress"
msgstr ""

#: pyanaconda/cmdline.py:89 pyanaconda/gui.py:1136
#: pyanaconda/kickstart.py:1167 pyanaconda/kickstart.py:1247
#: pyanaconda/kickstart.py:1255 pyanaconda/kickstart.py:1293
#: pyanaconda/kickstart.py:1301 pyanaconda/text.py:392
#, fuzzy, python-format
msgid ""
"The following error was found while parsing the kickstart configuration "
"file:\n"
"\n"
"%s"
msgstr ""
"جهلیگین خطا وهد وانگ پیداگ شمی تنظیمات kickstart :\n"
"\n"
"%s"

#: pyanaconda/cmdline.py:101
msgid ""
"Command line mode requires all choices to be specified in a kickstart "
"configuration file."
msgstr ""

#: pyanaconda/cmdline.py:120 pyanaconda/cmdline.py:127
#: pyanaconda/cmdline.py:134 pyanaconda/cmdline.py:141
msgid "Can't have a question in command line mode!"
msgstr ""

#: pyanaconda/constants.py:74
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report"
msgstr ""

#: pyanaconda/constants.py:80
msgid " with the provider of this software."
msgstr ""

#: pyanaconda/constants.py:84
#, python-format
msgid " against anaconda at %s"
msgstr ""

#: pyanaconda/gui.py:108
msgid "An error occurred saving screenshots to disk."
msgstr ""

#: pyanaconda/gui.py:125
msgid "Screenshots Copied"
msgstr ""

#: pyanaconda/gui.py:126
msgid ""
"The screenshots have been saved in the directory:\n"
"\n"
"\t/root/anaconda-screenshots/\n"
"\n"
"You can access these when you reboot and login as root."
msgstr ""

#: pyanaconda/gui.py:165
msgid "Saving Screenshot"
msgstr ""

#: pyanaconda/gui.py:166
#, python-format
msgid "A screenshot named '%s' has been saved."
msgstr ""

#: pyanaconda/gui.py:169
msgid "Error Saving Screenshot"
msgstr ""

#: pyanaconda/gui.py:170
msgid ""
"An error occurred while saving the screenshot.  If this occurred during "
"package installation, you may need to try several times for it to succeed."
msgstr ""

#: pyanaconda/gui.py:525 pyanaconda/text.py:150
msgid ""
"Choose a passphrase for the encrypted devices. You will be prompted for this "
"passphrase during system boot."
msgstr ""

#: pyanaconda/gui.py:544 pyanaconda/gui.py:552 pyanaconda/text.py:188
#: pyanaconda/text.py:198
msgid "Error with passphrase"
msgstr ""

#: pyanaconda/gui.py:545 pyanaconda/text.py:189
msgid "The passphrases you entered were different.  Please try again."
msgstr ""

#: pyanaconda/gui.py:553
msgid "The passphrase must be at least eight characters long."
msgstr ""

#: pyanaconda/gui.py:587 pyanaconda/text.py:226
#, python-format
msgid ""
"Device %s is encrypted. In order to access the device's contents during "
"installation you must enter the device's passphrase below."
msgstr ""

#: pyanaconda/gui.py:678 pyanaconda/gui.py:1342
#: pyanaconda/partIntfHelpers.py:153 pyanaconda/partIntfHelpers.py:338
#: pyanaconda/text.py:101 pyanaconda/text.py:102
#: pyanaconda/iw/account_gui.py:131 loader/dirbrowser.c:129
#: loader/driverdisk.c:409 loader/kickstart.c:382 loader/loader.c:469
#: loader/loader.c:581 pyanaconda/textw/constants_text.py:48
msgid "Cancel"
msgstr ""

#: pyanaconda/gui.py:690 pyanaconda/gui.py:691 pyanaconda/gui.py:809
#: pyanaconda/gui.py:810 data/ui/anaconda.glade.h:3
msgid "_Debug"
msgstr ""

#: pyanaconda/gui.py:933
msgid "Wireless setup"
msgstr ""

#: pyanaconda/gui.py:934
msgid "Scanning access points for wireless devices"
msgstr ""

#: pyanaconda/gui.py:960 pyanaconda/textw/netconfig_text.py:399
msgid "Waiting for NetworkManager"
msgstr ""

#: pyanaconda/gui.py:961
#, python-format
msgid "Waiting for NetworkManager to activate these devices: %s"
msgstr ""

#: pyanaconda/gui.py:982
#, python-format
msgid "Failed to activate these network interfaces: %s"
msgstr ""

#: pyanaconda/gui.py:985
msgid "Network Configuration"
msgstr ""

#: pyanaconda/gui.py:994 pyanaconda/iw/netconfig_dialog.py:213
#, python-format
msgid "An error occurred trying to bring up the %s network interface."
msgstr ""

#: pyanaconda/gui.py:996
msgid "Error Enabling Network"
msgstr ""

#: pyanaconda/gui.py:1082 pyanaconda/text.py:412
msgid ""
"You do not have an active network connection.  This is required by some "
"exception saving methods.  Would you like to configure your network now?"
msgstr ""

#: pyanaconda/gui.py:1088 pyanaconda/kickstart.py:150 pyanaconda/rescue.py:262
#: pyanaconda/text.py:418 pyanaconda/yuminstall.py:751
#: pyanaconda/yuminstall.py:1199 pyanaconda/iw/task_gui.py:311
msgid "No Network Available"
msgstr ""

#: pyanaconda/gui.py:1089 pyanaconda/text.py:419
msgid "Remote exception saving methods will not work."
msgstr ""

#: pyanaconda/gui.py:1138 pyanaconda/text.py:394
msgid "Error Parsing Kickstart Config"
msgstr ""

#: pyanaconda/gui.py:1166
msgid "default:LTR"
msgstr ""

#: pyanaconda/gui.py:1246 pyanaconda/text.py:511
msgid "Error!"
msgstr ""

#: pyanaconda/gui.py:1247 pyanaconda/text.py:512
#, python-format
msgid ""
"An error occurred when attempting to load an installer interface component.\n"
"\n"
"className = %s"
msgstr ""

#: pyanaconda/gui.py:1252 pyanaconda/image.py:163 pyanaconda/image.py:192
#: pyanaconda/packages.py:331 pyanaconda/storage/__init__.py:1817
msgid "_Exit"
msgstr ""

#: pyanaconda/gui.py:1253 pyanaconda/image.py:163 pyanaconda/image.py:192
#: pyanaconda/livecd.py:205 pyanaconda/yuminstall.py:835
#: pyanaconda/yuminstall.py:1221 pyanaconda/yuminstall.py:1275
#: pyanaconda/yuminstall.py:1482
msgid "_Retry"
msgstr ""

#: pyanaconda/gui.py:1255 pyanaconda/storage/partitioning.py:283
msgid "The system will now reboot."
msgstr ""

#: pyanaconda/gui.py:1256 pyanaconda/image.py:249 pyanaconda/packages.py:335
#: pyanaconda/yuminstall.py:1523
msgid "_Reboot"
msgstr ""

#: pyanaconda/gui.py:1258
msgid "Exiting"
msgstr ""

#: pyanaconda/gui.py:1339 pyanaconda/livecd.py:126 pyanaconda/text.py:271
#: pyanaconda/upgrade.py:245
msgid "Exit installer"
msgstr ""

#: pyanaconda/gui.py:1340
msgid "Are you sure you wish to exit the installer?"
msgstr ""

#: pyanaconda/gui.py:1349
#, python-format
msgid "%s Installer"
msgstr ""

#: pyanaconda/gui.py:1355
msgid "Unable to load title bar"
msgstr ""

#: pyanaconda/gui.py:1433
msgid "Install Window"
msgstr ""

#: pyanaconda/image.py:81
#, python-format
msgid ""
"The ISO image %s has a size which is not a multiple of 2048 bytes.  This may "
"mean it was corrupted on transfer to this computer.\n"
"\n"
"It is recommended that you exit and abort your installation, but you can "
"choose to continue if you think this is in error."
msgstr ""

#: pyanaconda/image.py:155
msgid "Couldn't Mount ISO Source"
msgstr ""

#: pyanaconda/image.py:156
#, python-format
msgid ""
"An error occurred mounting the source device %s.  This may happen if your "
"ISO images are located on an advanced storage device like LVM or RAID, or if "
"there was a problem mounting a partition.  Click exit to abort the "
"installation."
msgstr ""

#: pyanaconda/image.py:183
msgid "Missing ISO 9660 Image"
msgstr ""

#: pyanaconda/image.py:184
#, python-format
msgid ""
"The installer has tried to mount image #%s, but cannot find it on the hard "
"drive.\n"
"\n"
"Please copy this image to the drive and click Retry.  Click Exit to abort "
"the installation."
msgstr ""

#: pyanaconda/image.py:239
msgid "Required Install Media"
msgstr ""

#: pyanaconda/image.py:240
#, python-format
msgid ""
"The software you have selected to install will require the following "
"%(productName)s %(productVersion)s discs:\n"
"\n"
"%(reqcdstr)s\n"
"Please have these ready before proceeding with the installation.  If you "
"need to abort the installation and exit please select \"Reboot\"."
msgstr ""

#: pyanaconda/image.py:249 pyanaconda/livecd.py:446 pyanaconda/packages.py:335
#: pyanaconda/upgrade.py:253 pyanaconda/yuminstall.py:963
#: pyanaconda/yuminstall.py:1049 pyanaconda/yuminstall.py:1463
#: pyanaconda/yuminstall.py:1505 pyanaconda/yuminstall.py:1523
#: data/ui/anaconda.glade.h:2
msgid "_Back"
msgstr ""

#: pyanaconda/image.py:287
#, python-format
msgid ""
"An error occurred unmounting the disc.  Please make sure you're not "
"accessing %s from the shell on tty2 and then click OK to retry."
msgstr ""

#: pyanaconda/installclass.py:67
msgid "Install on System"
msgstr ""

#: pyanaconda/installinterfacebase.py:52
#, python-format
msgid ""
"Disk %s contains BIOS RAID metadata, but is not part of any recognized BIOS "
"RAID sets. Ignoring disk %s."
msgid_plural ""
"Disks %s contain BIOS RAID metadata, but are not part of any recognized BIOS "
"RAID sets. Ignoring disks %s."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/installinterfacebase.py:83
#, python-format
msgid ""
"Error processing drive:\n"
"\n"
"%(path)s\n"
"%(size)-0.fMB\n"
"%(description)s\n"
"\n"
"This device may need to be reinitialized.\n"
"\n"
"REINITIALIZING WILL CAUSE ALL DATA TO BE LOST!\n"
"\n"
"This action may also be applied to all other disks needing reinitialization."
"%(details)s"
msgstr ""

#: pyanaconda/installinterfacebase.py:92
#: pyanaconda/installinterfacebase.py:150
#: pyanaconda/installinterfacebase.py:184
msgid "_Ignore"
msgstr ""

#: pyanaconda/installinterfacebase.py:93
#: pyanaconda/installinterfacebase.py:151
msgid "Ignore _all"
msgstr ""

#: pyanaconda/installinterfacebase.py:94
#: pyanaconda/installinterfacebase.py:152
msgid "_Re-initialize"
msgstr ""

#: pyanaconda/installinterfacebase.py:95
#: pyanaconda/installinterfacebase.py:153
msgid "Re-ini_tialize all"
msgstr ""

#: pyanaconda/installinterfacebase.py:143
#, python-format
msgid ""
"Error processing LVM.\n"
"There is inconsistent LVM data on %(msg)s.  You can reinitialize all related "
"PVs (%(pvs)s) which will erase the LVM metadata, or ignore which will "
"preserve the contents.  This action may also be applied to all other PVs "
"with inconsistent metadata."
msgstr ""

#: pyanaconda/installinterfacebase.py:171
msgid "Unformatted DASD Device Found"
msgid_plural "Unformatted DASD Devices Found"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/installinterfacebase.py:173
#, python-format
msgid ""
"Format uninitialized DASD device?\n"
"\n"
"There is %d uninitialized DASD device on this system.  To continue "
"installation, the device must be formatted.  Formatting will remove any data "
"on this device."
msgid_plural ""
"Format uninitialized DASD devices?\n"
"\n"
"There are %d uninitialized DASD devices on this system.  To continue "
"installation, the devices must be formatted.  Formatting will remove any "
"data on these devices."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/installinterfacebase.py:184 pyanaconda/iw/partition_gui.py:898
msgid "_Format"
msgstr ""

#: pyanaconda/iutil.py:867
#, python-format
msgid ""
"Error: On open, cannot set reIPL method to %(reipl_type)s (%(filename)s: "
"%(e)s)"
msgstr ""

#: pyanaconda/iutil.py:878
#, python-format
msgid ""
"Error: On write, cannot set reIPL method to %(reipl_type)s (%(filename)s: "
"%(e)s)"
msgstr ""

#: pyanaconda/iutil.py:887
#, python-format
msgid ""
"Error: On close, cannot set reIPL method to %(reipl_type)s (%(filename)s: "
"%(e)s)"
msgstr ""

#: pyanaconda/iutil.py:906
#, python-format
msgid "Error: Could not set %(device)s as reIPL device (%(e)s)"
msgstr ""

#: pyanaconda/iutil.py:916
#, python-format
msgid "Error: Could not reset loadparm (%s)"
msgstr ""

#: pyanaconda/iutil.py:925
#, python-format
msgid "Warning: Could not reset parm (%s)"
msgstr ""

#: pyanaconda/iutil.py:938
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from DASD device %s to continue "
"installation"
msgstr ""

#: pyanaconda/iutil.py:960
#, python-format
msgid "Error: reading FCP property %(syspath_property)s for reIPL (%(e)s)"
msgstr ""

#: pyanaconda/iutil.py:975
#, python-format
msgid "Error: writing FCP property %(reipl_property)s for reIPL (%(e)s)"
msgstr ""

#: pyanaconda/iutil.py:990
#, python-format
msgid ""
"Error: writing default FCP property %(reipl_property)s for reIPL (%(e)s)"
msgstr ""

#: pyanaconda/iutil.py:1005
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from FCP %(device)s with WWPN "
"%(wwpn)s and LUN %(lun)s to continue installation"
msgstr ""

#: pyanaconda/iutil.py:1022
msgid ""
"After shutdown, please perform a manual IPL from the device now containing /"
"boot to continue installation"
msgstr ""

#: pyanaconda/iutil.py:1033
msgid "Error determining boot device's disk name"
msgstr ""

#: pyanaconda/iutil.py:1037
msgid "The mount point /boot or / is on a disk that we are not familiar with"
msgstr ""

#: pyanaconda/kickstart.py:115
#, fuzzy, python-format
msgid ""
"There was an error running the kickstart script at line %(lineno)s.  You may "
"examine the output in %(msgs)s.  This is a fatal error and installation will "
"be aborted.  Press the OK button to exit the installer."
msgstr ""
"نه تونیت ابزار اورش %s په %s کار بریت.\n"
"\n"
"هوبن آ بجنیت تا چه نصب کنوک در بیت"

#: pyanaconda/kickstart.py:123 pyanaconda/kickstart.py:125
msgid "Scriptlet Failure"
msgstr ""

#: pyanaconda/kickstart.py:151
msgid ""
"Encryption key escrow requires networking, but there was an error enabling "
"the network on your system."
msgstr ""

#: pyanaconda/kickstart.py:165
#, fuzzy, python-format
msgid ""
"The following error was encountered while downloading the escrow "
"certificate:\n"
"\n"
"%s"
msgstr ""
"جهلیگین خطا وهد وانگ پیداگ شمی تنظیمات kickstart :\n"
"\n"
"%s"

#: pyanaconda/kickstart.py:1266
#, python-format
msgid "Error processing %%ksappend lines: %s"
msgstr "خطا په پردازش %%ksappend lines: %s"

#: pyanaconda/kickstart.py:1269
#, python-format
msgid "Unknown error processing %%ksappend lines: %s"
msgstr "نا شناسین خطا پردازشی %%ksappend lines: %s"

#: pyanaconda/kickstart.py:1324 pyanaconda/livecd.py:228
msgid "Post-Installation"
msgstr ""

#: pyanaconda/kickstart.py:1325
msgid "Running post-installation scripts"
msgstr ""

#: pyanaconda/kickstart.py:1341
msgid "Pre-Installation"
msgstr ""

#: pyanaconda/kickstart.py:1342
msgid "Running pre-installation scripts"
msgstr ""

#: pyanaconda/kickstart.py:1374
msgid "Missing Package"
msgstr ""

#: pyanaconda/kickstart.py:1375
#, python-format
msgid ""
"You have specified that the package '%s' should be installed.  This package "
"does not exist. Would you like to continue or abort this installation?"
msgstr ""

#: pyanaconda/kickstart.py:1381 pyanaconda/kickstart.py:1420
msgid "_Abort"
msgstr ""

#: pyanaconda/kickstart.py:1382 pyanaconda/kickstart.py:1421
msgid "_Ignore All"
msgstr ""

#: pyanaconda/kickstart.py:1412
msgid "Missing Group"
msgstr ""

#: pyanaconda/kickstart.py:1413
#, python-format
msgid ""
"You have specified that the group '%s' should be installed. This group does "
"not exist. Would you like to continue or abort this installation?"
msgstr ""

#: pyanaconda/kickstart.py:1511
#, python-format
msgid ""
"The kickstart configuration file is missing required information that "
"anaconda cannot prompt for.  Please add the following sections and try "
"again:\n"
"%s"
msgstr ""

#: pyanaconda/livecd.py:121
msgid "Unable to find image"
msgstr ""

#: pyanaconda/livecd.py:122
#, python-format
msgid ""
"The given location isn't a valid %s live CD to use as an installation source."
msgstr ""

#: pyanaconda/livecd.py:180
msgid "Copying live image to hard drive."
msgstr ""

#: pyanaconda/livecd.py:199
msgid ""
"There was an error installing the live image to your hard drive.  This could "
"be due to bad media.  Please verify your installation media.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"require reinstallation."
msgstr ""

#: pyanaconda/livecd.py:229
msgid ""
"Performing post-installation filesystem changes.  This may take several "
"minutes."
msgstr ""

#: pyanaconda/livecd.py:441
#, python-format
msgid ""
"The root filesystem you created is not large enough for this live image "
"(%.2f MB required)."
msgstr ""

#: pyanaconda/network.py:63
msgid "Hostname must be 255 or fewer characters in length."
msgstr ""

#: pyanaconda/network.py:69
msgid ""
"Hostname must start with a valid character in the ranges 'a-z', 'A-Z', or "
"'0-9'"
msgstr ""

#: pyanaconda/network.py:74
msgid ""
"Hostnames can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.'"
msgstr ""

#: pyanaconda/network.py:118
msgid "IP address is missing."
msgstr ""

#: pyanaconda/network.py:122
msgid ""
"IPv4 addresses must contain four numbers between 0 and 255, separated by "
"periods."
msgstr ""

#: pyanaconda/network.py:125
#, python-format
msgid "'%s' is not a valid IPv6 address."
msgstr ""

#: pyanaconda/network.py:127
#, python-format
msgid "'%s' is an invalid IP address."
msgstr ""

#: pyanaconda/packages.py:112
msgid "Resizing Failed"
msgstr ""

#: pyanaconda/packages.py:113
#, python-format
msgid "There was an error encountered while resizing the device %s."
msgstr ""

#: pyanaconda/packages.py:121
msgid "Migration Failed"
msgstr ""

#: pyanaconda/packages.py:122
#, python-format
msgid "An error was encountered while migrating filesystem on device %s."
msgstr ""

#: pyanaconda/packages.py:131
msgid "_File Bug"
msgstr ""

#: pyanaconda/packages.py:315
#, python-format
msgid ""
"Warning!  This is pre-release software!\n"
"\n"
"Thank you for downloading this pre-release of %(productName)s.\n"
"\n"
"This is not a final release and is not intended for use on production "
"systems.  The purpose of this release is to collect feedback from testers, "
"and it is not suitable for day to day usage.\n"
"\n"
"To report feedback, please visit:\n"
"\n"
"   %(bugzillaUrl)s\n"
"\n"
"and file a report against '%(fileagainst)s'.\n"
msgstr ""

#: pyanaconda/packages.py:331
msgid "_Install Anyway"
msgstr ""

#: pyanaconda/packages.py:334
msgid "Your system will now be rebooted..."
msgstr ""

#: pyanaconda/packages.py:336
msgid "Warning! This is pre-release software!"
msgstr ""

#: pyanaconda/partIntfHelpers.py:41
msgid "Please enter a volume group name."
msgstr ""

#: pyanaconda/partIntfHelpers.py:45
msgid "Volume Group Names must be less than 128 characters"
msgstr ""

#: pyanaconda/partIntfHelpers.py:48
#, python-format
msgid "Error - the volume group name %s is not valid."
msgstr ""

#: pyanaconda/partIntfHelpers.py:53
msgid ""
"Error - the volume group name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""

#: pyanaconda/partIntfHelpers.py:63
msgid "Please enter a logical volume name."
msgstr ""

#: pyanaconda/partIntfHelpers.py:67
msgid "Logical Volume Names must be less than 128 characters"
msgstr ""

#: pyanaconda/partIntfHelpers.py:71
#, python-format
msgid "Error - the logical volume name %s is not valid."
msgstr ""

#: pyanaconda/partIntfHelpers.py:77
msgid ""
"Error - the logical volume name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""

#: pyanaconda/partIntfHelpers.py:105
#, python-format
msgid ""
"The mount point %s is invalid.  Mount points must start with '/' and cannot "
"end with '/', and must contain printable characters and no spaces."
msgstr ""

#: pyanaconda/partIntfHelpers.py:117 pyanaconda/partIntfHelpers.py:124
msgid "Unable To Delete"
msgstr ""

#: pyanaconda/partIntfHelpers.py:118
msgid "You must first select a partition to delete."
msgstr ""

#: pyanaconda/partIntfHelpers.py:149 pyanaconda/partIntfHelpers.py:337
#: pyanaconda/iw/lvm_dialog_gui.py:877
msgid "Confirm Delete"
msgstr ""

#: pyanaconda/partIntfHelpers.py:150
#, python-format
msgid "You are about to delete all partitions on the device '%s'."
msgstr ""

#: pyanaconda/partIntfHelpers.py:153 pyanaconda/partIntfHelpers.py:338
#: pyanaconda/iw/lvm_dialog_gui.py:880 pyanaconda/iw/lvm_dialog_gui.py:1450
#: pyanaconda/iw/osbootwidget.py:104 pyanaconda/iw/partition_gui.py:1812
#: pyanaconda/iw/partition_gui.py:1824
msgid "_Delete"
msgstr ""

#: pyanaconda/partIntfHelpers.py:200
msgid "Notice"
msgstr ""

#: pyanaconda/partIntfHelpers.py:201
#, python-format
msgid ""
"The following partitions were not deleted because they are in use:\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/partIntfHelpers.py:216
msgid "Format as Swap?"
msgstr ""

#: pyanaconda/partIntfHelpers.py:217
#, python-format
msgid ""
"%s has a partition type of 0x82 (Linux swap) but does not appear to be "
"formatted as a Linux swap partition.\n"
"\n"
"Would you like to format this partition as a swap partition?"
msgstr ""

#: pyanaconda/partIntfHelpers.py:232
#, python-format
msgid "You need to select at least one hard drive to install %s."
msgstr ""

#: pyanaconda/partIntfHelpers.py:237
msgid ""
"You have chosen to use a pre-existing partition for this installation "
"without formatting it. We recommend that you format this partition to make "
"sure files from a previous operating system installation do not cause "
"problems with this installation of Linux. However, if this partition "
"contains files that you need to keep, such as home directories, then "
"continue without formatting this partition."
msgstr ""

#: pyanaconda/partIntfHelpers.py:245
msgid "Format?"
msgstr ""

#: pyanaconda/partIntfHelpers.py:245 pyanaconda/iw/partition_gui.py:1597
msgid "_Modify Partition"
msgstr ""

#: pyanaconda/partIntfHelpers.py:245
msgid "Do _Not Format"
msgstr ""

#: pyanaconda/partIntfHelpers.py:253
msgid "Error with Partitioning"
msgstr ""

#: pyanaconda/partIntfHelpers.py:254
#, python-format
msgid ""
"The following critical errors exist with your requested partitioning scheme. "
"These errors must be corrected prior to continuing with your install of "
"%(productName)s.\n"
"\n"
"%(errorstr)s"
msgstr ""

#: pyanaconda/partIntfHelpers.py:270
msgid "Partitioning Warning"
msgstr ""

#: pyanaconda/partIntfHelpers.py:271
#, python-format
msgid ""
"The following warnings exist with your requested partition scheme.\n"
"\n"
"%s\n"
"\n"
"Would you like to continue with your requested partitioning scheme?"
msgstr ""

#: pyanaconda/partIntfHelpers.py:285
msgid ""
"The following pre-existing partitions have been selected to be formatted, "
"destroying all data."
msgstr ""

#: pyanaconda/partIntfHelpers.py:288
msgid ""
"Select 'Yes' to continue and format these partitions, or 'No' to go back and "
"change these settings."
msgstr ""

#: pyanaconda/partIntfHelpers.py:294
msgid "Format Warning"
msgstr ""

#: pyanaconda/partIntfHelpers.py:321
#, python-format
msgid ""
"You are about to delete the volume group \"%s\".\n"
"\n"
"ALL logical volumes in this volume group will be lost!"
msgstr ""

#: pyanaconda/partIntfHelpers.py:325
#, python-format
msgid "You are about to delete the logical volume \"%s\"."
msgstr ""

#: pyanaconda/partIntfHelpers.py:328
msgid "You are about to delete a RAID device."
msgstr ""

#: pyanaconda/partIntfHelpers.py:330
#, python-format
msgid "You are about to delete the %s partition."
msgstr ""

#: pyanaconda/partIntfHelpers.py:334
#, python-format
msgid "You are about to delete the %(type)s %(name)s"
msgstr ""

#: pyanaconda/partIntfHelpers.py:345
msgid "Confirm Reset"
msgstr ""

#: pyanaconda/partIntfHelpers.py:346
msgid ""
"Are you sure you want to reset the partition table to its original state?"
msgstr ""

#: pyanaconda/platform.py:98 pyanaconda/platform.py:344
#: pyanaconda/platform.py:412 pyanaconda/platform.py:520
#: data/ui/create-storage.glade.h:15
msgid "RAID Device"
msgstr ""

#: pyanaconda/platform.py:99 pyanaconda/platform.py:102
#: pyanaconda/platform.py:345 pyanaconda/platform.py:413
#: pyanaconda/platform.py:521 pyanaconda/platform.py:524
msgid "Master Boot Record (MBR)"
msgstr ""

#: pyanaconda/platform.py:101 pyanaconda/platform.py:523
msgid "First sector of boot partition"
msgstr ""

#: pyanaconda/platform.py:113
msgid "You have not created a bootable partition."
msgstr ""

#: pyanaconda/platform.py:118
msgid "Bootable partitions cannot be on a RAID device."
msgstr ""

#: pyanaconda/platform.py:120
msgid "Bootable partitions can only be on RAID1 devices."
msgstr ""

#: pyanaconda/platform.py:124
msgid "Bootable RAID1 set members must be partitions."
msgstr ""

#: pyanaconda/platform.py:129
msgid "Bootable partitions cannot be on a logical volume."
msgstr ""

#: pyanaconda/platform.py:136
#, python-format
msgid "Bootable partitions cannot be on an %s filesystem."
msgstr ""

#: pyanaconda/platform.py:140 pyanaconda/platform.py:145
msgid "Bootable partitions cannot be on an encrypted block device"
msgstr ""

#: pyanaconda/platform.py:217
msgid "EFI System Partition"
msgstr ""

#: pyanaconda/platform.py:229
msgid "You have not created a /boot/efi partition."
msgstr ""

#: pyanaconda/platform.py:235
msgid "/boot/efi is not EFI."
msgstr ""

#: pyanaconda/platform.py:251
#, python-format
msgid "%s must have a %s disk label."
msgstr ""

#: pyanaconda/platform.py:289
#, python-format
msgid "%s must have a bsd disk label."
msgstr ""

#: pyanaconda/platform.py:301
#, python-format
msgid "The disk %s requires at least 1MB of free space at the beginning."
msgstr ""

#: pyanaconda/platform.py:347
msgid "PPC PReP Boot"
msgstr ""

#: pyanaconda/platform.py:363
msgid "The boot partition must be within the first 4MB of the disk."
msgstr ""

#: pyanaconda/platform.py:415 pyanaconda/platform.py:418
msgid "Apple Bootstrap"
msgstr ""

#: pyanaconda/platform.py:432
#, python-format
msgid "%s must have a mac disk label."
msgstr ""

#: pyanaconda/rescue.py:221
msgid "When finished please exit from the shell and your system will reboot."
msgstr ""

#: pyanaconda/rescue.py:235
msgid "Unable to find /bin/sh to execute!  Not starting shell"
msgstr ""

#: pyanaconda/rescue.py:254
msgid "Setup Networking"
msgstr ""

#: pyanaconda/rescue.py:255
msgid "Do you want to start the network interfaces on this system?"
msgstr ""

#: pyanaconda/rescue.py:256 loader/driverdisk.c:649 loader/driverdisk.c:659
#: loader/hdinstall.c:212 pyanaconda/textw/constants_text.py:56
msgid "Yes"
msgstr ""

#: pyanaconda/rescue.py:256 pyanaconda/rescue.py:258 loader/driverdisk.c:649
#: loader/driverdisk.c:659 pyanaconda/textw/constants_text.py:60
msgid "No"
msgstr ""

#: pyanaconda/rescue.py:263
msgid ""
"Unable to activate a networking device.  Networking will not be available in "
"rescue mode."
msgstr ""

#: pyanaconda/rescue.py:299 pyanaconda/rescue.py:374 pyanaconda/rescue.py:385
#: pyanaconda/rescue.py:470 pyanaconda/rescue.py:499
msgid "Rescue"
msgstr ""

#: pyanaconda/rescue.py:300
#, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory %s.  You can then make any changes required to "
"your system.  If you want to proceed with this step choose 'Continue'.  You "
"can also choose to mount your file systems read-only instead of read-write "
"by choosing 'Read-Only'.  If you need to activate SAN devices choose "
"'Advanced'.\n"
"\n"
"If for some reason this process fails you can choose 'Skip' and this step "
"will be skipped and you will go directly to a command shell.\n"
"\n"
msgstr ""

#: pyanaconda/rescue.py:311 pyanaconda/iw/partition_gui.py:785
#: loader/cdinstall.c:207 loader/cdinstall.c:215 loader/driverdisk.c:610
#: pyanaconda/storage/__init__.py:169 pyanaconda/storage/devicetree.py:90
msgid "Continue"
msgstr ""

#: pyanaconda/rescue.py:311 pyanaconda/rescue.py:320
msgid "Read-Only"
msgstr ""

#: pyanaconda/rescue.py:311 pyanaconda/rescue.py:313 loader/cdinstall.c:249
#: loader/cdinstall.c:252 loader/method.c:333
#: pyanaconda/storage/__init__.py:1817 pyanaconda/textw/upgrade_text.py:139
msgid "Skip"
msgstr ""

#: pyanaconda/rescue.py:311 pyanaconda/rescue.py:316
msgid "Advanced"
msgstr ""

#: pyanaconda/rescue.py:350
msgid "System to Rescue"
msgstr ""

#: pyanaconda/rescue.py:351
msgid "Which device holds the root partition of your installation?"
msgstr ""

#: pyanaconda/rescue.py:353 pyanaconda/rescue.py:357 pyanaconda/text.py:516
#: pyanaconda/text.py:518
msgid "Exit"
msgstr ""

#: pyanaconda/rescue.py:375
msgid ""
"Your system had dirty file systems which you chose not to mount.  Press "
"return to get a shell from which you can fsck and mount your partitions.  "
"The system will reboot automatically when you exit from the shell."
msgstr ""

#: pyanaconda/rescue.py:386
#, python-format
msgid ""
"Your system has been mounted under %(rootPath)s.\n"
"\n"
"Press <return> to get a shell. If you would like to make your system the "
"root environment, run the command:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"The system will reboot automatically when you exit from the shell."
msgstr ""

#: pyanaconda/rescue.py:471
#, python-format
msgid ""
"An error occurred trying to mount some or all of your system. Some of it may "
"be mounted under %s.\n"
"\n"
"Press <return> to get a shell. The system will reboot automatically when you "
"exit from the shell."
msgstr ""

#: pyanaconda/rescue.py:481
msgid "You don't have any Linux partitions.  Rebooting.\n"
msgstr ""

#: pyanaconda/rescue.py:484
msgid "Rescue Mode"
msgstr ""

#: pyanaconda/rescue.py:485
msgid ""
"You don't have any Linux partitions. Press return to get a shell. The system "
"will reboot automatically when you exit from the shell."
msgstr ""

#: pyanaconda/rescue.py:498
#, python-format
msgid "Your system is mounted under the %s directory."
msgstr ""

#: pyanaconda/text.py:155
msgid "Passphrase for encrypted device"
msgstr ""

#: pyanaconda/text.py:168
msgid "Also add this passphrase to all existing encrypted devices"
msgstr ""

#: pyanaconda/text.py:199
#, python-format
msgid "The passphrase must be at least %d character long."
msgid_plural "The passphrase must be at least %d characters long."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/text.py:233 data/ui/lukspassphrase.glade.h:6
msgid "Passphrase"
msgstr ""

#: pyanaconda/text.py:241 data/ui/lukspassphrase.glade.h:7
msgid "This is a global passphrase"
msgstr ""

#: pyanaconda/text.py:356 pyanaconda/text.py:360
msgid "Repository editing is not available in text mode."
msgstr ""

#: pyanaconda/text.py:437
#, python-format
msgid "Welcome to %(productName)s for %(productArch)s"
msgstr ""

#: pyanaconda/text.py:439
#, python-format
msgid "Welcome to %s"
msgstr ""

#: pyanaconda/text.py:441
msgid ""
"  <Tab>/<Alt-Tab> between elements   |  <Space> selects   |  <F12> next "
"screen"
msgstr ""

#: pyanaconda/text.py:516 loader/net.c:110 loader/net.c:513 loader/net.c:568
#: loader/net.c:710 loader/net.c:718 loader/net.c:1148 loader/net.c:1156
msgid "Retry"
msgstr ""

#: pyanaconda/text.py:530
msgid "Cancelled"
msgstr ""

#: pyanaconda/text.py:531
msgid "I can't go to the previous step from here. You will have to try again."
msgstr ""

#: pyanaconda/upgrade.py:51
msgid "Proceed with upgrade?"
msgstr ""

#: pyanaconda/upgrade.py:52
msgid ""
"The file systems of the Linux installation you have chosen to upgrade have "
"already been mounted. You cannot go back past this point. \n"
"\n"
msgstr ""

#: pyanaconda/upgrade.py:56
msgid "Would you like to continue with the upgrade?"
msgstr ""

#: pyanaconda/upgrade.py:91
msgid "Cannot Upgrade"
msgstr ""

#: pyanaconda/upgrade.py:92
#, python-format
msgid ""
"Your current installation cannot be upgraded. This is likely due to it being "
"too old. Only the previous two release may be upgraded. To upgrade older "
"releases you must first upgrade through all intermediate releases.\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/upgrade.py:232
msgid "Mount failed"
msgstr ""

#: pyanaconda/upgrade.py:233
#, python-format
msgid ""
"The following error occurred when mounting the file systems listed in /etc/"
"fstab.  Please fix this problem and try to upgrade again.\n"
"%s"
msgstr ""

#: pyanaconda/upgrade.py:241 pyanaconda/upgrade.py:248
msgid "Upgrade root not found"
msgstr ""

#: pyanaconda/upgrade.py:242
msgid "The root for the previously installed system was not found."
msgstr ""

#: pyanaconda/upgrade.py:249
msgid ""
"The root for the previously installed system was not found.  You can exit "
"installer or backtrack to choose installation instead of upgrade."
msgstr ""

#: pyanaconda/upgrade.py:272
msgid ""
"The following files are absolute symbolic links, which we do not support "
"during an upgrade. Please change them to relative symbolic links and restart "
"the upgrade.\n"
"\n"
msgstr ""

#: pyanaconda/upgrade.py:278
msgid "Absolute Symlinks"
msgstr ""

#: pyanaconda/upgrade.py:289
msgid ""
"The following are directories which should instead be symbolic links, which "
"will cause problems with the upgrade.  Please return them to their original "
"state as symbolic links and restart the upgrade.\n"
"\n"
msgstr ""

#: pyanaconda/upgrade.py:295
msgid "Invalid Directories"
msgstr ""

#: pyanaconda/vnc.py:140
#, python-format
msgid "%(productName)s %(productVersion)s installation on host %(name)s"
msgstr ""

#: pyanaconda/vnc.py:146
#, python-format
msgid "%(productName)s %(productVersion)s installation"
msgstr ""

#: pyanaconda/vnc.py:175
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr ""

#: pyanaconda/vnc.py:189
msgid "Connected!"
msgstr ""

#: pyanaconda/vnc.py:192
msgid "Will try to connect again in 15 seconds..."
msgstr ""

#: pyanaconda/vnc.py:198
#, python-format
msgid "Giving up attempting to connect after %d try!\n"
msgid_plural "Giving up attempting to connect after %d tries!\n"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/vnc.py:209
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr ""

#: pyanaconda/vnc.py:211
msgid "Please manually connect your vnc client to begin the install."
msgstr ""

#: pyanaconda/vnc.py:214
msgid "Starting VNC..."
msgstr ""

#: pyanaconda/vnc.py:239
msgid "The VNC server is now running."
msgstr ""

#: pyanaconda/vnc.py:252
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""

#: pyanaconda/vnc.py:257
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""

#: pyanaconda/vnc.py:261
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""

#: pyanaconda/vnc.py:263
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr ""

#: pyanaconda/vnc.py:285 pyanaconda/vnc.py:378
msgid "VNC Configuration"
msgstr ""

#: pyanaconda/vnc.py:288 pyanaconda/vnc.py:382
msgid "No password"
msgstr ""

#: pyanaconda/vnc.py:290 pyanaconda/vnc.py:385
msgid ""
"A password will prevent unauthorized listeners connecting and monitoring "
"your installation progress.  Please enter a password to be used for the "
"installation"
msgstr ""

#: pyanaconda/vnc.py:298 pyanaconda/vnc.py:393
#: pyanaconda/textw/userauth_text.py:47
msgid "Password:"
msgstr ""

#: pyanaconda/vnc.py:299 pyanaconda/vnc.py:394
#: pyanaconda/textw/userauth_text.py:49
msgid "Password (confirm):"
msgstr ""

#: pyanaconda/vnc.py:317 pyanaconda/vnc.py:416
#: pyanaconda/textw/userauth_text.py:70
msgid "Password Mismatch"
msgstr ""

#: pyanaconda/vnc.py:318 pyanaconda/vnc.py:417
#: pyanaconda/textw/userauth_text.py:71
msgid "The passwords you entered were different. Please try again."
msgstr ""

#: pyanaconda/vnc.py:323 pyanaconda/vnc.py:422
#: pyanaconda/textw/userauth_text.py:66
msgid "Password Length"
msgstr ""

#: pyanaconda/vnc.py:324 pyanaconda/vnc.py:423
msgid "The password must be at least six characters long."
msgstr ""

#: pyanaconda/vnc.py:346
msgid "Unable to Start X"
msgstr ""

#: pyanaconda/vnc.py:348
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"install or continue with a text mode install?"
msgstr ""

#: pyanaconda/vnc.py:367
msgid "Start VNC"
msgstr ""

#: pyanaconda/vnc.py:368 pyanaconda/vnc.py:370
msgid "Use text mode"
msgstr ""

#: pyanaconda/yuminstall.py:85
#, python-format
msgid "%s MB"
msgstr ""

#: pyanaconda/yuminstall.py:88
#, python-format
msgid "%s KB"
msgstr ""

#: pyanaconda/yuminstall.py:90
#, python-format
msgid "%s Byte"
msgid_plural "%s Bytes"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/yuminstall.py:134
msgid "Preparing to install"
msgstr ""

#: pyanaconda/yuminstall.py:135
msgid "Preparing transaction from installation source"
msgstr ""

#: pyanaconda/yuminstall.py:163
#, python-format
msgid "<b>Installing %(pkgStr)s</b> (%(size)s)\n"
msgstr ""

#: pyanaconda/yuminstall.py:212
#, python-format
msgid "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgid_plural "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/yuminstall.py:227
msgid "Finishing upgrade"
msgstr ""

#: pyanaconda/yuminstall.py:228
msgid "Finishing upgrade process.  This may take a little while."
msgstr ""

#: pyanaconda/yuminstall.py:251
msgid "Error Installing Package"
msgstr ""

#: pyanaconda/yuminstall.py:252
#, python-format
msgid ""
"A fatal error occurred when installing the %s package.  This could indicate "
"errors when reading the installation media.  Installation cannot continue."
msgstr ""

#: pyanaconda/yuminstall.py:402 pyanaconda/iw/task_gui.py:324
msgid "Error Setting Up Repository"
msgstr ""

#: pyanaconda/yuminstall.py:403
#, fuzzy, python-format
msgid ""
"The following error occurred while setting up the installation repository:\n"
"\n"
"%(e)s\n"
"\n"
"Please provide the correct information for installing %(productName)s."
msgstr ""
"جهلیگین خطا گون شمی پارتیشن گنگ پیش آتک:\n"
"\n"
"%s\n"
"\n"
"هوبنت آ بجنیت تا چه نصب کنوک در بیت."

#: pyanaconda/yuminstall.py:448
msgid "Change Disc"
msgstr ""

#: pyanaconda/yuminstall.py:449
#, python-format
msgid "Please insert %(productName)s disc %(discnum)d to continue."
msgstr ""

#: pyanaconda/yuminstall.py:459
msgid "Wrong Disc"
msgstr ""

#: pyanaconda/yuminstall.py:460
#, python-format
msgid "That's not the correct %s disc."
msgstr ""

#: pyanaconda/yuminstall.py:467
msgid "Unable to access the disc."
msgstr ""

#: pyanaconda/yuminstall.py:631
#, python-format
msgid "Repository %r is missing name in configuration, using id"
msgstr ""

#: pyanaconda/yuminstall.py:752 pyanaconda/yuminstall.py:1200
#: pyanaconda/iw/task_gui.py:312
msgid ""
"Some of your software repositories require networking, but there was an "
"error enabling the network on your system."
msgstr ""

#: pyanaconda/yuminstall.py:833 pyanaconda/yuminstall.py:835
msgid "Re_boot"
msgstr ""

#: pyanaconda/yuminstall.py:833
msgid "_Eject"
msgstr ""

#: pyanaconda/yuminstall.py:839
#, python-format
msgid ""
"The file %s cannot be opened.  This is due to a missing file, a corrupt "
"package or corrupt media.  Please verify your installation source.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"likely require reinstallation.\n"
"\n"
msgstr ""

#: pyanaconda/yuminstall.py:887
msgid "Retrying"
msgstr ""

#: pyanaconda/yuminstall.py:887
msgid "Retrying download."
msgstr ""

#: pyanaconda/yuminstall.py:952
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s\n"
msgstr ""

#: pyanaconda/yuminstall.py:995 pyanaconda/yuminstall.py:996
msgid "file conflicts"
msgstr ""

#: pyanaconda/yuminstall.py:997
msgid "older package(s)"
msgstr ""

#: pyanaconda/yuminstall.py:998
msgid "insufficient disk space"
msgstr ""

#: pyanaconda/yuminstall.py:999
msgid "insufficient disk inodes"
msgstr ""

#: pyanaconda/yuminstall.py:1000
msgid "package conflicts"
msgstr ""

#: pyanaconda/yuminstall.py:1001
msgid "package already installed"
msgstr ""

#: pyanaconda/yuminstall.py:1002
msgid "required package"
msgstr ""

#: pyanaconda/yuminstall.py:1003
msgid "package for incorrect arch"
msgstr ""

#: pyanaconda/yuminstall.py:1004
msgid "package for incorrect os"
msgstr ""

#: pyanaconda/yuminstall.py:1018
msgid "You need more space on the following file systems:\n"
msgstr ""

#: pyanaconda/yuminstall.py:1031
#, python-format
msgid ""
"There were file conflicts when checking the packages to be installed:\n"
"%s\n"
msgstr ""

#: pyanaconda/yuminstall.py:1034
#, python-format
msgid ""
"There was an error running your transaction for the following reason(s): "
"%s.\n"
msgstr ""

#: pyanaconda/yuminstall.py:1041 pyanaconda/yuminstall.py:1046
msgid "Error Running Transaction"
msgstr ""

#: pyanaconda/yuminstall.py:1226
msgid ""
"Unable to read group information from repositories.  This is a problem with "
"the generation of your install tree."
msgstr ""

#: pyanaconda/yuminstall.py:1275 pyanaconda/textw/constants_text.py:64
msgid "Edit"
msgstr ""

#: pyanaconda/yuminstall.py:1286 pyanaconda/yuminstall.py:1477
#, python-format
msgid ""
"Unable to read package metadata. This may be due to a missing repodata "
"directory.  Please ensure that your install tree has been correctly "
"generated.\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/yuminstall.py:1455
msgid ""
"Some of the packages you have selected for install are missing "
"dependencies.  You can exit the installation, go back and change your "
"package selections, or continue installing these packages without their "
"dependencies.  If you continue, these packages may not work correctly due to "
"missing components."
msgstr ""

#: pyanaconda/yuminstall.py:1499
#, python-format
msgid ""
"Your selected packages require %d MB of free space for installation, but you "
"do not have enough available.  You can change your selections or exit the "
"installer."
msgstr ""

#: pyanaconda/yuminstall.py:1520
msgid "Reboot?"
msgstr ""

#: pyanaconda/yuminstall.py:1521
msgid "The system will be rebooted now."
msgstr ""

#: pyanaconda/yuminstall.py:1663
#, python-format
msgid ""
"You appear to be upgrading from a system which is too old to upgrade to this "
"version of %s.  Are you sure you wish to continue the upgrade process?"
msgstr ""

#: pyanaconda/yuminstall.py:1698
#, python-format
msgid ""
"The arch of the release of %(productName)s you are upgrading to appears to "
"be %(myarch)s which does not match your previously installed arch of "
"%(arch)s.  This is likely to not succeed.  Are you sure you wish to continue "
"the upgrade process?"
msgstr ""

#: pyanaconda/yuminstall.py:1745
msgid "Post Upgrade"
msgstr ""

#: pyanaconda/yuminstall.py:1746
msgid "Performing post-upgrade configuration"
msgstr ""

#: pyanaconda/yuminstall.py:1748
msgid "Post Installation"
msgstr ""

#: pyanaconda/yuminstall.py:1749
msgid "Performing post-installation configuration"
msgstr ""

#: pyanaconda/yuminstall.py:1990
msgid "Installation Starting"
msgstr ""

#: pyanaconda/yuminstall.py:1991
#, fuzzy
msgid "Starting installation process"
msgstr "گرافیکی نصب شروع بیگنت..."

#: pyanaconda/yuminstall.py:2029
msgid "Dependency Check"
msgstr ""

#: pyanaconda/yuminstall.py:2030
msgid "Checking dependencies in packages selected for installation"
msgstr ""

#: pyanaconda/yuminstall.py:2086 pyanaconda/yuminstall.py:2102
msgid "Retrieving installation information."
msgstr ""

#: pyanaconda/yuminstall.py:2088 pyanaconda/yuminstall.py:2104
#, python-format
msgid "Retrieving installation information for %s."
msgstr ""

#: pyanaconda/yuminstall.py:2089 pyanaconda/yuminstall.py:2105
msgid "Installation Progress"
msgstr ""

#: pyanaconda/installclasses/fedora.py:38
msgid "_Fedora"
msgstr ""

#: pyanaconda/installclasses/fedora.py:39
#, python-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage. You can optionally select a different set of "
"software now."
msgstr ""

#: pyanaconda/installclasses/fedora.py:48
msgid "Graphical Desktop"
msgstr ""

#: pyanaconda/installclasses/fedora.py:53
msgid "Software Development"
msgstr ""

#: pyanaconda/installclasses/fedora.py:59
msgid "Web Server"
msgstr ""

#: pyanaconda/installclasses/fedora.py:63 pyanaconda/installclasses/rhel.py:44
msgid "Minimal"
msgstr ""

#: pyanaconda/installclasses/rhel.py:33
msgid "Red Hat Enterprise Linux"
msgstr ""

#: pyanaconda/installclasses/rhel.py:34
#, python-format
msgid ""
"The default installation of %s is a minimum install. You can optionally "
"select a different set of software now."
msgstr ""

#: pyanaconda/iw/GroupSelector.py:147
#, python-format
msgid "Packages in %s"
msgstr ""

#: pyanaconda/iw/GroupSelector.py:433
#, python-format
msgid "Optional packages selected: %(inst)d of %(cnt)d"
msgstr ""

#: pyanaconda/iw/GroupSelector.py:435
#, python-format
msgid "<i>%s</i>"
msgstr ""

#: pyanaconda/iw/GroupSelector.py:495
msgid "Uncategorized"
msgstr ""

#: pyanaconda/iw/account_gui.py:52
msgid "Root _Password:"
msgstr ""

#: pyanaconda/iw/account_gui.py:54
msgid "_Confirm:"
msgstr ""

#: pyanaconda/iw/account_gui.py:92
msgid "Caps Lock is on."
msgstr ""

#: pyanaconda/iw/account_gui.py:102 pyanaconda/iw/account_gui.py:110
#: pyanaconda/iw/account_gui.py:117 pyanaconda/iw/account_gui.py:138
#: pyanaconda/textw/userauth_text.py:74
msgid "Error with Password"
msgstr ""

#: pyanaconda/iw/account_gui.py:103
msgid ""
"You must enter your root password and confirm it by typing it a second time "
"to continue."
msgstr ""

#: pyanaconda/iw/account_gui.py:111
msgid "The passwords you entered were different.  Please try again."
msgstr ""

#: pyanaconda/iw/account_gui.py:118
msgid "The root password must be at least six characters long."
msgstr ""

#: pyanaconda/iw/account_gui.py:127 pyanaconda/textw/userauth_text.py:83
msgid "Weak Password"
msgstr ""

#: pyanaconda/iw/account_gui.py:128
#, python-format
msgid "You have provided a weak password: %s"
msgstr ""

#: pyanaconda/iw/account_gui.py:131
msgid "_Use Anyway"
msgstr ""

#: pyanaconda/iw/account_gui.py:139 pyanaconda/textw/userauth_text.py:75
msgid ""
"Requested password contains non-ASCII characters, which are not allowed."
msgstr ""

#: pyanaconda/iw/advanced_storage.py:87
msgid "You must select a NIC to use."
msgstr ""

#: pyanaconda/iw/advanced_storage.py:132
msgid "Invalid Initiator Name"
msgstr ""

#: pyanaconda/iw/advanced_storage.py:133
msgid "You must provide an initiator name."
msgstr ""

#: pyanaconda/iw/advanced_storage.py:162
msgid "Error with Data"
msgstr ""

#: pyanaconda/iw/autopart_type.py:96
msgid ""
"No partitions are available to resize.  Only physical partitions with "
"specific filesystems can be resized."
msgstr ""

#: pyanaconda/iw/autopart_type.py:119
msgid "Resize FileSystem Error"
msgstr ""

#: pyanaconda/iw/autopart_type.py:120
#, python-format
msgid "%(device)s: %(msg)s"
msgstr ""

#: pyanaconda/iw/autopart_type.py:129
msgid "Resize Device Error"
msgstr ""

#: pyanaconda/iw/autopart_type.py:130
#, python-format
msgid "%(name)s: %(msg)s"
msgstr ""

#: pyanaconda/iw/autopart_type.py:250
msgid "Use All Space"
msgstr ""

#: pyanaconda/iw/autopart_type.py:252
msgid ""
"Removes all partitions on the selected device(s).  This includes partitions "
"created by other operating systems.\n"
"\n"
"<b>Tip:</b> This option will remove data from the selected device(s).  Make "
"sure you have backups."
msgstr ""

#: pyanaconda/iw/autopart_type.py:258
msgid "Replace Existing Linux System(s)"
msgstr ""

#: pyanaconda/iw/autopart_type.py:260
msgid ""
"Removes all Linux partitions on the selected device(s). This does not remove "
"other partitions you may have on your storage device(s) (such as VFAT or "
"FAT32).\n"
"\n"
"<b>Tip:</b> This option will remove data from the selected device(s).  Make "
"sure you have backups."
msgstr ""

#: pyanaconda/iw/autopart_type.py:268
msgid "Shrink Current System"
msgstr ""

#: pyanaconda/iw/autopart_type.py:270
msgid ""
"Shrinks existing partitions to create free space for the default layout."
msgstr ""

#: pyanaconda/iw/autopart_type.py:272
msgid "Use Free Space"
msgstr ""

#: pyanaconda/iw/autopart_type.py:274
msgid ""
"Retains your current data and partitions and uses only the unpartitioned "
"space on the selected device(s), assuming you have enough free space "
"available."
msgstr ""

#: pyanaconda/iw/autopart_type.py:278
msgid "Create Custom Layout"
msgstr ""

#: pyanaconda/iw/autopart_type.py:280
msgid ""
"Manually create your own custom layout on the selected device(s) using our "
"partitioning tool."
msgstr ""

#: pyanaconda/iw/blpasswidget.py:44
msgid "_Use a boot loader password"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:45
msgid ""
"A boot loader password prevents users from changing kernel options, "
"increasing security."
msgstr ""

#: pyanaconda/iw/blpasswidget.py:76
msgid "Change _password"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:99
msgid "Enter Boot Loader Password"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:105
msgid ""
"Enter a boot loader password and then confirm it.  (Note that your BIOS "
"keymap may be different than the actual keymap you are used to.)"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:112
msgid "_Password:"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:118
msgid "Con_firm:"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:139
msgid "Passwords don't match"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:140
msgid "Passwords do not match"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:149
msgid ""
"Your boot loader password is shorter than six characters.  We recommend a "
"longer boot loader password.\n"
"\n"
"Would you like to continue with this password?"
msgstr ""

#: pyanaconda/iw/bootloader_main_gui.py:36
msgid "Boot Loader Configuration"
msgstr ""

#: pyanaconda/iw/bootloader_main_gui.py:180
#: pyanaconda/iw/bootloader_main_gui.py:185
#: pyanaconda/iw/bootloader_main_gui.py:223
#, python-format
msgid "_Install boot loader on /dev/%s."
msgstr ""

#: pyanaconda/iw/bootloader_main_gui.py:229
msgid "_Change device"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:34
msgid "Clear Disks Selector"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:45 pyanaconda/iw/filter_gui.py:432
msgid "You must select at least one drive to be used for installation."
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:55
msgid "You must select one drive to boot from."
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:127 pyanaconda/iw/cleardisks_gui.py:147
#: pyanaconda/iw/filter_gui.py:489 pyanaconda/iw/filter_gui.py:500
#: pyanaconda/iw/filter_gui.py:530
msgid "Model"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:128 pyanaconda/iw/cleardisks_gui.py:148
#: pyanaconda/iw/filter_gui.py:490 pyanaconda/iw/filter_gui.py:501
#: pyanaconda/iw/filter_gui.py:509 pyanaconda/iw/filter_gui.py:520
#: pyanaconda/iw/filter_gui.py:531
msgid "Capacity"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:129 pyanaconda/iw/filter_gui.py:491
#: pyanaconda/iw/filter_gui.py:510 pyanaconda/iw/filter_gui.py:521
#: pyanaconda/iw/filter_gui.py:532
msgid "Vendor"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:130 pyanaconda/iw/cleardisks_gui.py:149
#: pyanaconda/iw/filter_gui.py:508 pyanaconda/iw/filter_gui.py:519
#: pyanaconda/iw/filter_gui.py:535
msgid "Identifier"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:131 pyanaconda/iw/filter_gui.py:492
#: pyanaconda/iw/filter_gui.py:511 pyanaconda/iw/filter_gui.py:522
#: pyanaconda/iw/filter_gui.py:533
msgid "Interconnect"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:145
msgid ""
"Boot\n"
"Loader"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:196
msgid ""
"<b>Tip:</b> All Linux filesystems on the install target devices will be "
"reformatted and wiped of any data.  Make sure you have backups."
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:198
msgid ""
"<b>Tip:</b> The install target devices will be reformatted and wiped of any "
"data.  Make sure you have backups."
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:200
msgid ""
"<b>Tip:</b> Your filesystems on the install target devices will not be "
"reformatted unless you choose to do so during customization."
msgstr ""

#: pyanaconda/iw/congrats_gui.py:33
msgid "Congratulations"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:74 pyanaconda/textw/complete_text.py:39
#, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:77 pyanaconda/textw/complete_text.py:42
msgid "Shutdown"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:79 pyanaconda/textw/complete_text.py:44
msgid "Please shutdown to use the installed system.\n"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:81 pyanaconda/textw/complete_text.py:46
msgid "Please reboot to use the installed system.\n"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:86 pyanaconda/textw/complete_text.py:51
msgid ""
"Note that updates may be available to ensure the proper functioning of your "
"system and installation of these updates is recommended after the reboot."
msgstr ""

#: pyanaconda/iw/congrats_gui.py:90 pyanaconda/textw/complete_text.py:55
#, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
"Please reboot to use the installed system.  Note that updates may be "
"available to ensure the proper functioning of your system and installation "
"of these updates is recommended after the reboot."
msgstr ""

#: pyanaconda/iw/examine_gui.py:39
msgid "Upgrade Examine"
msgstr ""

#: pyanaconda/iw/examine_gui.py:58
msgid "Fresh Installation"
msgstr ""

#: pyanaconda/iw/examine_gui.py:60
#, python-format
msgid ""
"Choose this option to install a fresh copy of %s on your system.  Existing "
"software and data may be overwritten depending on your configuration choices."
msgstr ""

#: pyanaconda/iw/examine_gui.py:65
msgid "Upgrade an Existing Installation"
msgstr ""

#: pyanaconda/iw/examine_gui.py:67
#, python-format
msgid ""
"Choose this option if you would like to upgrade your existing %s system.  "
"This option will preserve the existing data on your storage device(s)."
msgstr ""

#: pyanaconda/iw/examine_gui.py:117
msgid ""
"At least one existing installation has been detected on your system.  What "
"would you like to do?"
msgstr ""

#: pyanaconda/iw/examine_gui.py:136
#, python-format
msgid "<b>Which %s installation would you like to upgrade?</b>"
msgstr ""

#: pyanaconda/iw/examine_gui.py:150
msgid "Unknown Linux system"
msgstr ""

#: pyanaconda/iw/filter_gui.py:150
#, python-format
msgid "Selected devices: %s (%s MB) out of %s (%s MB)."
msgstr ""

#: pyanaconda/iw/filter_gui.py:400
msgid "Device Filter"
msgstr ""

#: pyanaconda/iw/filter_gui.py:493 pyanaconda/iw/filter_gui.py:523
#: pyanaconda/iw/filter_gui.py:534
msgid "Serial Number"
msgstr ""

#: pyanaconda/iw/filter_gui.py:494 pyanaconda/iw/filter_gui.py:502
#: pyanaconda/iw/filter_gui.py:513 pyanaconda/iw/filter_gui.py:524
#: pyanaconda/iw/filter_gui.py:539 pyanaconda/iw/osbootwidget.py:66
#: pyanaconda/iw/partition_gui.py:611
msgid "Device"
msgstr ""

#: pyanaconda/iw/filter_gui.py:512
msgid "Paths"
msgstr ""

#: pyanaconda/iw/filter_gui.py:536
msgid "Port"
msgstr ""

#: pyanaconda/iw/filter_gui.py:537
msgid "Target"
msgstr ""

#: pyanaconda/iw/filter_gui.py:538
msgid "LUN"
msgstr ""

#: pyanaconda/iw/filter_type.py:55
msgid "What type of devices will your installation involve?"
msgstr ""

#: pyanaconda/iw/filter_type.py:61
msgid "Basic Storage Devices"
msgstr ""

#: pyanaconda/iw/filter_type.py:62
msgid ""
"Installs or upgrades to typical types of storage devices.  If you're not "
"sure which option is right for you, this is probably it."
msgstr ""

#: pyanaconda/iw/filter_type.py:66
msgid "Specialized Storage Devices"
msgstr ""

#: pyanaconda/iw/filter_type.py:67
msgid ""
"Installs or upgrades to enterprise devices such as Storage Area Networks "
"(SANs). This option will allow you to add FCoE / iSCSI / zFCP disks and to "
"filter out devices the installer should ignore."
msgstr ""

#: pyanaconda/iw/language_gui.py:33 pyanaconda/textw/language_text.py:45
msgid "Language Selection"
msgstr ""

#: pyanaconda/iw/language_gui.py:81 loader/lang.c:371
#: pyanaconda/textw/language_text.py:46
msgid "What language would you like to use during the installation process?"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:126 pyanaconda/iw/lvm_dialog_gui.py:172
#: pyanaconda/iw/lvm_dialog_gui.py:186 pyanaconda/iw/lvm_dialog_gui.py:225
#: pyanaconda/iw/lvm_dialog_gui.py:302 pyanaconda/iw/lvm_dialog_gui.py:697
#: pyanaconda/iw/lvm_dialog_gui.py:718
msgid "Not enough space"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:127
msgid ""
"The physical extent size cannot be changed because otherwise the space "
"required by the currently defined logical volumes will be increased to more "
"than the available space."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:136
msgid "Confirm Physical Extent Change"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:137
msgid ""
"This change in the value of the physical extent will require the sizes of "
"the current logical volume requests to be rounded up in size to an integer "
"multiple of the physical extent.\n"
"\n"
"This change will take effect immediately."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:146 pyanaconda/iw/lvm_dialog_gui.py:208
msgid "C_ontinue"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:173
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected "
"(%(curpe)10.2f MB) is larger than the smallest physical volume "
"(%(maxpvsize)10.2f MB) in the volume group."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:187
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected "
"(%(curpe)10.2f MB) is too large compared to the size of the smallest "
"physical volume (%(maxpvsize)10.2f MB) in the volume group."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:201
msgid "Too small"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:202
msgid ""
"This change in the value of the physical extent will waste substantial space "
"on one or more of the physical volumes in the volume group."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:226
#, python-format
msgid ""
"The physical extent size cannot be changed because the resulting maximum "
"logical volume size (%10.2f MB) is smaller than one or more of the currently "
"defined logical volumes."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:303
msgid ""
"You cannot remove this physical volume because otherwise the volume group "
"will be too small to hold the currently defined logical volumes."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:402
msgid "Make Logical Volume"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:404
#, python-format
msgid "Edit Logical Volume: %s"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:443 pyanaconda/iw/raid_dialog_gui.py:451
msgid "_File System Type:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:449
msgid "_Logical Volume Name:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:458
#: pyanaconda/iw/partition_dialog_gui.py:492
msgid "_Size (MB):"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:465
#, python-format
msgid "(Max size is %s MB)"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:470
#: pyanaconda/iw/partition_dialog_gui.py:544
#: pyanaconda/iw/partition_ui_helpers_gui.py:337
#: pyanaconda/iw/raid_dialog_gui.py:423
msgid "_Encrypt"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:479
#: pyanaconda/iw/partition_dialog_gui.py:474
#: pyanaconda/iw/raid_dialog_gui.py:461
msgid "Original File System Type:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:484
#: pyanaconda/iw/partition_dialog_gui.py:482
#: pyanaconda/iw/raid_dialog_gui.py:468
msgid "Original File System Label:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:489
msgid "Logical Volume Name:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:493
msgid "Size (MB):"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:520
#: pyanaconda/iw/partition_dialog_gui.py:430
#: pyanaconda/iw/raid_dialog_gui.py:442
msgid "_Mount Point:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:601
#: pyanaconda/iw/partition_dialog_gui.py:118
#: pyanaconda/iw/raid_dialog_gui.py:176
msgid "Mount Point Error"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:611
msgid "Illegal Logical Volume Name"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:626
msgid "Illegal logical volume name"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:627
#, python-format
msgid "The logical volume name \"%s\" is already in use. Please pick another."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:668
#: pyanaconda/iw/partition_dialog_gui.py:133
#: pyanaconda/iw/raid_dialog_gui.py:191
msgid "Mount point in use"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:669
#: pyanaconda/iw/partition_dialog_gui.py:134
#: pyanaconda/iw/raid_dialog_gui.py:192
#, python-format
msgid "The mount point \"%s\" is in use. Please pick another."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:684
msgid "Illegal size"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:685
msgid "The requested size as entered is not a valid number greater than 0."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:698
#, python-format
msgid ""
"The current requested size (%(size)10.2f MB) is larger than the maximum "
"logical volume size (%(maxlv)10.2f MB). To increase this limit you can "
"create more Physical Volumes from unpartitioned disk space and add them to "
"this Volume Group."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:719
#, python-format
msgid ""
"The size entered for this logical volume (%(size)d MB) combined with the "
"size of the other logical volume(s) exceeds the size of the volume group "
"(%(tempvgsize)d MB). Please make the volume group larger or make the logical "
"volume smaller."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:829
msgid "No free slots"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:830
#, python-format
msgid "You cannot create more than %d logical volume per volume group."
msgid_plural "You cannot create more than %d logical volumes per volume group."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/iw/lvm_dialog_gui.py:840
msgid "No free space"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:841
msgid ""
"There is no room left in the volume group to create new logical volumes. To "
"add a logical volume you must reduce the size of one or more of the "
"currently existing logical volumes"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:878
#, python-format
msgid "Are you sure you want to delete the logical volume \"%s\"?"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:984
msgid "Invalid Volume Group Name"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:993
msgid "Name in use"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:994
#, python-format
msgid "The volume group name \"%s\" is already in use. Please pick another."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1281
msgid "Not enough physical volumes"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1282
msgid ""
"At least one unused physical volume partition is needed to create an LVM "
"Volume Group.\n"
"\n"
"Create a partition or RAID array of type \"physical volume (LVM)\" and then "
"select the \"LVM\" option again."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1293
msgid "Make LVM Volume Group"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1296
#, python-format
msgid "Edit LVM Volume Group: %s"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1298
msgid "Edit LVM Volume Group"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1314
msgid "_Volume Group Name:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1322
msgid "Volume Group Name:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1330
msgid "_Physical Extent:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1345
msgid "Physical Volumes to _Use:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1351
msgid "Used Space:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1368
msgid "Free Space:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1386
msgid "Total Space:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1424
msgid "Logical Volume Name"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1427 pyanaconda/iw/partition_gui.py:614
#: pyanaconda/iw/upgrade_swap_gui.py:138 pyanaconda/textw/upgrade_text.py:124
msgid "Mount Point"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1430 pyanaconda/iw/partition_gui.py:613
msgid "Size (MB)"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1444 pyanaconda/iw/osbootwidget.py:96
msgid "_Add"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1447 pyanaconda/iw/osbootwidget.py:100
#: pyanaconda/iw/partition_gui.py:1811 pyanaconda/iw/partition_gui.py:1821
msgid "_Edit"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1462
msgid "_Logical Volumes"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:192 pyanaconda/textw/netconfig_text.py:36
#, python-format
msgid ""
"An error occurred converting the value entered for \"%(field)s\":\n"
"%(errmsg)s"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:195 pyanaconda/iw/netconfig_dialog.py:204
#: pyanaconda/textw/netconfig_text.py:35 pyanaconda/textw/netconfig_text.py:42
msgid "Error With Data"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:203
#, python-format
msgid "A value is required for the field %s."
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:215
msgid "Error Configuring Network"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:241
msgid "Dynamic IP Address"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:242
#, python-format
msgid "Sending request for IP address information for %s"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:257 pyanaconda/iw/netconfig_dialog.py:260
msgid "IP Address"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:267
#: pyanaconda/textw/netconfig_text.py:290
msgid "IPv4 CIDR prefix must be between 0 and 32."
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:268 pyanaconda/iw/netconfig_dialog.py:274
#: pyanaconda/iw/netconfig_dialog.py:282 pyanaconda/iw/netconfig_dialog.py:285
msgid "IPv4 Network Mask"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:295
msgid "Gateway"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:305
msgid "Nameserver"
msgstr ""

#: pyanaconda/iw/netconfig_dialog.py:314
msgid "Error configuring network device:"
msgstr ""

#: pyanaconda/iw/network_gui.py:83 pyanaconda/iw/network_gui.py:89
msgid "Error with Hostname"
msgstr ""

#: pyanaconda/iw/network_gui.py:84
msgid "You must enter a valid hostname for this computer."
msgstr ""

#: pyanaconda/iw/network_gui.py:90
#, python-format
msgid ""
"The hostname \"%(hostname)s\" is not valid for the following reason:\n"
"\n"
"%(herrors)s"
msgstr ""

#: pyanaconda/iw/network_gui.py:134
msgid "Select network interface"
msgstr ""

#: pyanaconda/iw/network_gui.py:141 data/ui/netconfig.glade.h:10
msgid ""
"This requires that you have an active network connection during the "
"installation process.  Please configure a network interface."
msgstr ""

#: pyanaconda/iw/network_gui.py:211
msgid "Select APs"
msgstr ""

#: pyanaconda/iw/network_gui.py:218
msgid "Select APs for wireless devices"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:50
msgid "Boot loader operating system list"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:66
msgid "Default"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:66 pyanaconda/iw/partition_gui.py:612
msgid "Label"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:130
msgid "Image"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:137
msgid ""
"Enter a label for the boot loader menu to display. The device (or hard drive "
"and partition number) is the device from which it boots."
msgstr ""

#: pyanaconda/iw/osbootwidget.py:145
msgid "_Label"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:153
msgid "_Device"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:183
msgid "Default Boot _Target"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:212
msgid "You must specify a label for the entry"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:221
msgid "Boot label contains illegal characters"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:245
msgid "Duplicate Label"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:246
msgid "This label is already in use for another boot entry."
msgstr ""

#: pyanaconda/iw/osbootwidget.py:259
msgid "Duplicate Device"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:260
msgid "This device is already being used for another boot entry."
msgstr ""

#: pyanaconda/iw/osbootwidget.py:322
msgid "Cannot Delete"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:323
#, python-format
msgid ""
"This boot target cannot be deleted because it is for the %s system you are "
"about to install."
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:58
msgid "Additional Size Options"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:63
msgid "_Fixed size"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:65
msgid "Fill all space _up to (MB):"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:72
msgid "Fill to maximum _allowable size"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:191
msgid "Error With Request"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:400
msgid "Add Partition"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:402
#, python-format
msgid "Edit Partition: %s"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:439
msgid "File System _Type:"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:455
msgid "Allowable _Drives:"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:531
msgid "Force to be a _primary partition"
msgstr ""

#: pyanaconda/iw/partition_gui.py:360
#, python-format
msgid "Drive %(drive)s (%(size)-0.f MB) (Model: %(model)s)"
msgstr ""

#: pyanaconda/iw/partition_gui.py:400 pyanaconda/iw/partition_gui.py:446
#: pyanaconda/iw/partition_gui.py:513 pyanaconda/iw/partition_gui.py:998
#: pyanaconda/iw/partition_gui.py:1070
msgid "Free"
msgstr ""

#: pyanaconda/iw/partition_gui.py:478
#, python-format
msgid "LVM Volume Group %s (%-0.f MB)"
msgstr ""

#: pyanaconda/iw/partition_gui.py:544
#, python-format
msgid "MD RAID ARRAY %s (%-0.f MB)"
msgstr ""

#: pyanaconda/iw/partition_gui.py:615
msgid "Type"
msgstr ""

#: pyanaconda/iw/partition_gui.py:616 pyanaconda/storage/__init__.py:1817
msgid "Format"
msgstr ""

#: pyanaconda/iw/partition_gui.py:653
msgid ""
"Mount Point/\n"
"RAID/Volume"
msgstr ""

#: pyanaconda/iw/partition_gui.py:655
msgid ""
"Size\n"
"(MB)"
msgstr ""

#: pyanaconda/iw/partition_gui.py:760
msgid "Partitioning"
msgstr ""

#: pyanaconda/iw/partition_gui.py:850
msgid ""
"The partitioning scheme you requested caused the following critical errors."
msgstr ""

#: pyanaconda/iw/partition_gui.py:852
#, python-format
msgid ""
"You must correct these errors before you continue your installation of %s."
msgstr ""

#: pyanaconda/iw/partition_gui.py:858
msgid "Partitioning Errors"
msgstr ""

#: pyanaconda/iw/partition_gui.py:865
msgid "The partitioning scheme you requested generated the following warnings."
msgstr ""

#: pyanaconda/iw/partition_gui.py:867
msgid "Would you like to continue with your requested partitioning scheme?"
msgstr ""

#: pyanaconda/iw/partition_gui.py:872
msgid "Partitioning Warnings"
msgstr ""

#: pyanaconda/iw/partition_gui.py:881
msgid ""
"The following pre-existing devices have been selected to be formatted, "
"destroying all data."
msgstr ""

#: pyanaconda/iw/partition_gui.py:893
msgid "Format Warnings"
msgstr ""

#: pyanaconda/iw/partition_gui.py:986
msgid "LVM Volume Groups"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1008
msgid "RAID Devices"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1024 loader/hdinstall.c:212
msgid "Hard Drives"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1074
msgid "Extended"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1364
msgid "Cannot perform any creation action"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1365
msgid ""
"Note that the creation action requires one of the following:\n"
"\n"
"* Free space in one of the Hard Drives.\n"
"* At least two free Software RAID partitions.\n"
"* At least one free physical volume (LVM) partition.\n"
"* At least one Volume Group with free space."
msgstr ""

#: pyanaconda/iw/partition_gui.py:1468
#, python-format
msgid ""
"Software RAID allows you to combine several disks into a larger RAID "
"device.  A RAID device can be configured to provide additional speed and "
"reliability compared to using an individual drive.  For more information on "
"using RAID devices please consult the %s documentation.\n"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1474
msgid ""
"To use RAID you must first create at least two partitions of type 'software "
"RAID'.  Then you can create a RAID device that can be formatted and "
"mounted.\n"
"\n"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1478
#, python-format
msgid "You currently have %d software RAID partition free to use."
msgid_plural "You currently have %d software RAID partitions free to use."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/iw/partition_gui.py:1482
msgid "About RAID"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1488
#, python-format
msgid ""
"Logical Volume Manager (LVM) is a 3 level construct. The first level is made "
"up of disks or partitions formatted with LVM metadata called Physical "
"Volumes (PV).  A Volume Group (VG) sits on top of one or more PVs. The VG, "
"in turn, is the base to create one or more Logical Volumes (LV).  Note that "
"a VG can be an aggregate of PVs from multiple physical disks.  For more "
"information on using LVM please consult the %s documentation\n"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1496
msgid ""
"To create a PV you need a partition with free space.  To create a VG you "
"need a PV that is not part of any existing VG.  To create an LV you need a "
"VG with free space.\n"
"\n"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1500
#, python-format
msgid "You currently have %d available PV free to use.\n"
msgid_plural "You currently have %d available PVs free to use.\n"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/iw/partition_gui.py:1504
msgid "You currently have free space to create PVs."
msgstr ""

#: pyanaconda/iw/partition_gui.py:1507
msgid "About LVM"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1585 pyanaconda/storage/partitioning.py:203
#: pyanaconda/storage/partitioning.py:246
msgid "Error Partitioning"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1586
#, python-format
msgid "Could not allocate requested partitions: %s."
msgstr ""

#: pyanaconda/iw/partition_gui.py:1595
#, python-format
msgid "Warning: %s."
msgstr ""

#: pyanaconda/iw/partition_gui.py:1626
msgid "Unable To Edit"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1627
#, python-format
msgid ""
"You cannot edit this device:\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1810
msgid "_Create"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1813
msgid "Re_set"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1836
msgid "Please Select A Device"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:110
#: pyanaconda/iw/partition_ui_helpers_gui.py:132
#: pyanaconda/iw/partition_ui_helpers_gui.py:134
msgid "<Not Applicable>"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:318
msgid "_Format as:"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:340
msgid "Mi_grate filesystem to:"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:370
msgid "_Resize"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:425
#, python-format
msgid ""
"Partitions of type '%s' must be constrained to a single drive.  To do this, "
"select the drive in the 'Allowable Drives' checklist."
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:390
msgid ""
"At least two unused software RAID partitions are needed to create a RAID "
"device.\n"
"\n"
"First create at least two partitions of type \"software RAID\", and then "
"select the \"RAID\" option again."
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:404
msgid "Make RAID Device"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:407
#, python-format
msgid "Edit RAID Device: %s"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:409
msgid "Edit RAID Device"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:476
msgid "RAID _Device:"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:494
msgid "RAID _Level:"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:536
msgid "_RAID Members:"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:553
msgid "Number of _spares:"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:563
msgid "_Format partition?"
msgstr ""

#: pyanaconda/iw/task_gui.py:55
#, python-format
msgid ""
"Unable to read package metadata from repository.  This may be due to a "
"missing repodata directory.  Please ensure that your repository has been "
"correctly generated.\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/iw/task_gui.py:129
msgid "Edit Repository"
msgstr ""

#: pyanaconda/iw/task_gui.py:153
#, python-format
msgid ""
"The repository %s has already been added.  Please choose a different "
"repository name and URL."
msgstr ""

#: pyanaconda/iw/task_gui.py:239
msgid "Invalid Proxy URL"
msgstr ""

#: pyanaconda/iw/task_gui.py:240
msgid "You must provide an HTTP, HTTPS, or FTP URL to a proxy."
msgstr ""

#: pyanaconda/iw/task_gui.py:252 pyanaconda/iw/task_gui.py:436
msgid "Invalid Repository URL"
msgstr ""

#: pyanaconda/iw/task_gui.py:253 pyanaconda/iw/task_gui.py:437
msgid "You must provide an HTTP, HTTPS, or FTP URL to a repository."
msgstr ""

#: pyanaconda/iw/task_gui.py:274 pyanaconda/iw/task_gui.py:446
msgid "No Media Found"
msgstr ""

#: pyanaconda/iw/task_gui.py:275 pyanaconda/iw/task_gui.py:447
msgid ""
"No installation media was found. Please insert a disc into your drive and "
"try again."
msgstr ""

#: pyanaconda/iw/task_gui.py:306 pyanaconda/iw/task_gui.py:470
msgid "Please enter an NFS server and path."
msgstr ""

#: pyanaconda/iw/task_gui.py:325
#, fuzzy, python-format
msgid ""
"The following error occurred while setting up the repository:\n"
"\n"
"%s"
msgstr ""
"جهلیگین خطا وهد وانگ پیداگ شمی تنظیمات kickstart :\n"
"\n"
"%s"

#: pyanaconda/iw/task_gui.py:348
msgid "Invalid Repository Name"
msgstr ""

#: pyanaconda/iw/task_gui.py:349
msgid "You must provide a repository name."
msgstr ""

#: pyanaconda/iw/task_gui.py:502 data/ui/addrepo.glade.h:3
msgid "Add Repository"
msgstr ""

#: pyanaconda/iw/task_gui.py:507
msgid "No Software Repos Enabled"
msgstr ""

#: pyanaconda/iw/task_gui.py:508
msgid ""
"You must have at least one software repository enabled to continue "
"installation."
msgstr ""

#: pyanaconda/iw/timezone_gui.py:63 pyanaconda/textw/timezone_text.py:95
msgid "Time Zone Selection"
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:37
#: pyanaconda/textw/upgrade_bootloader_text.py:129
msgid "Upgrade Boot Loader Configuration"
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:120
msgid "_Update boot loader configuration"
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:121
msgid "This will update your current boot loader."
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:125
#: pyanaconda/textw/upgrade_bootloader_text.py:103
msgid ""
"Due to system changes, your boot loader configuration can not be "
"automatically updated."
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:128
#: pyanaconda/textw/upgrade_bootloader_text.py:107
msgid ""
"The installer is unable to detect the boot loader currently in use on your "
"system."
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:135
#: pyanaconda/textw/upgrade_bootloader_text.py:116
#, python-format
msgid ""
"The installer has detected the %(type)s boot loader currently installed on "
"%(bootDev)s."
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:139
msgid "This is the recommended option."
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:144
msgid "_Create new boot loader configuration"
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:146
msgid ""
"This option creates a new boot loader configuration.  If you wish to switch "
"boot loaders, you should choose this."
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:153
msgid "_Skip boot loader updating"
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:154
msgid ""
"This option makes no changes to boot loader configuration.  If you are using "
"a third party boot loader, you should choose this."
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:165
msgid "What would you like to do?"
msgstr ""

#: pyanaconda/iw/upgrade_migratefs_gui.py:38
#: pyanaconda/textw/upgrade_text.py:42
msgid "Migrate File Systems"
msgstr ""

#: pyanaconda/iw/upgrade_migratefs_gui.py:69
#: pyanaconda/textw/upgrade_text.py:44
#, python-format
msgid ""
"This release of %(productName)s supports an updated file system, which has "
"several benefits over the file system traditionally shipped in "
"%(productName)s.  This installation program can migrate formatted partitions "
"without data loss.\n"
"\n"
"Which of these partitions would you like to migrate?"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:35
msgid "Upgrade Swap Partition"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:92 pyanaconda/textw/upgrade_text.py:107
#, python-format
msgid ""
"Recent kernels (2.4 or newer) need significantly more swap than older "
"kernels, up to twice the amount of RAM on the system.  You currently have "
"%dMB of swap configured, but you may create additional swap space on one of "
"your file systems now."
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:99
#, python-format
msgid ""
"\n"
"\n"
"The installer has detected %s MB of RAM.\n"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:111
msgid "I _want to create a swap file"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:120
msgid "Select the _partition to put the swap file on:"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:138 pyanaconda/textw/upgrade_text.py:125
msgid "Partition"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:138
msgid "Free Space (MB)"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:156
#, python-format
msgid ""
"A minimum swap file size of %d MB is recommended.  Please enter a size for "
"the swap file:"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:171
msgid "Swap file _size (MB):"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:181
msgid "I _don't want to create a swap file"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:191
msgid ""
"A swap file is strongly recommended. Failure to create one could cause the "
"installer to abort abnormally.  Are you sure you wish to continue?"
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:199 pyanaconda/textw/upgrade_text.py:194
msgid "The swap file must be between 1 and 2000 MB in size."
msgstr ""

#: pyanaconda/iw/upgrade_swap_gui.py:206 pyanaconda/textw/upgrade_text.py:189
msgid ""
"There is not enough space on the device you selected for the swap partition."
msgstr ""

#: pyanaconda/iw/welcome_gui.py:56 pyanaconda/textw/welcome_text.py:36
msgid "Network Install Required"
msgstr ""

#: pyanaconda/iw/welcome_gui.py:57 pyanaconda/textw/welcome_text.py:37
msgid ""
"Your installation source is set to a network location, but no network "
"devices were found on your system.  To avoid a network installation, boot "
"with the full DVD, full CD set, or do not pass a repo= parameter that "
"specifies a network source."
msgstr ""

#: pyanaconda/iw/welcome_gui.py:67
#, fuzzy
msgid "E_xit Installer"
msgstr "دست بروگا تنظیم کتن"

#: pyanaconda/iw/zipl_gui.py:37
msgid "z/IPL Boot Loader Configuration"
msgstr ""

#: pyanaconda/iw/zipl_gui.py:61
msgid "The z/IPL boot loader will be installed on your system."
msgstr ""

#: pyanaconda/iw/zipl_gui.py:63
msgid ""
"The z/IPL Boot Loader will now be installed on your system.\n"
"\n"
"The root partition will be the one you selected previously in the partition "
"setup.\n"
"\n"
"The kernel used to start the machine will be the one to be installed by "
"default.\n"
"\n"
"If you wish to make changes later after the installation feel free to change "
"the /etc/zipl.conf configuration file.\n"
"\n"
"You can now enter any additional kernel parameters which your machine or "
"your setup may require."
msgstr ""

#: pyanaconda/iw/zipl_gui.py:90 pyanaconda/textw/zipl_text.py:72
msgid "Kernel Parameters"
msgstr ""

#: pyanaconda/iw/zipl_gui.py:93 pyanaconda/iw/zipl_gui.py:96
msgid "Chandev Parameters"
msgstr ""

#: loader/net.h:27 pyanaconda/textw/netconfig_text.py:164
#, fuzzy
msgid "Dynamic IP configuration (DHCP)"
msgstr "ـ داینامیکی آی ‍پی کارمز کنت(DHCP) "

#: loader/net.h:28
#, fuzzy
msgid "Manual configuration"
msgstr "دستی تنظیم گنگ"

#: loader/net.h:30
#, fuzzy
msgid "Dynamic IP configuration (DHCPv6)"
msgstr "ـ داینامیکی آی ‍پی کارمز کنت(DHCP) "

#: loader/net.h:31 pyanaconda/textw/netconfig_text.py:201
msgid "Automatic neighbor discovery"
msgstr ""

#: loader/cdinstall.c:186 loader/cdinstall.c:207 loader/mediacheck.c:61
msgid "Media Check"
msgstr ""

#: loader/cdinstall.c:186 loader/cdinstall.c:189 loader/cdinstall.c:207
#: loader/cdinstall.c:215 loader/method.c:333
msgid "Test"
msgstr ""

#: loader/cdinstall.c:186 loader/cdinstall.c:190
msgid "Eject Disc"
msgstr ""

#: loader/cdinstall.c:187
#, c-format
msgid ""
"Choose \"%s\" to test the disc currently in the drive, or \"%s\" to eject "
"the disc and insert another for testing."
msgstr ""

#: loader/cdinstall.c:208
#, c-format
msgid ""
"If you would like to test additional media, insert the next disc and press "
"\"%s\". Testing each disc is not strictly required, however it is highly "
"recommended.  Minimally, the discs should be tested prior to using them for "
"the first time. After they have been successfully tested, it is not required "
"to retest each disc prior to using it again."
msgstr ""

#: loader/cdinstall.c:230
#, c-format
msgid ""
"The %s disc was not found in any of your drives. Please insert the %s disc "
"and press %s to retry."
msgstr ""

#: loader/cdinstall.c:249
msgid "Disc Found"
msgstr ""

#: loader/cdinstall.c:250
#, c-format
msgid ""
"To begin testing the media before installation press %s.\n"
"\n"
"Choose %s to skip the media test and start the installation."
msgstr ""

#: loader/cdinstall.c:331
msgid "Scanning"
msgstr ""

#: loader/cdinstall.c:331
#, c-format
msgid "Looking for installation images on CD device %s\n"
msgstr ""

#: loader/cdinstall.c:333
#, c-format
msgid "Looking for installation images on CD device %s"
msgstr ""

#: loader/cdinstall.c:425
#, c-format
msgid ""
"The %s disc was not found in any of your CDROM drives. Please insert the %s "
"disc and press %s to retry."
msgstr ""

#: loader/cdinstall.c:431
msgid "Disc Not Found"
msgstr ""

#: loader/cdinstall.c:432 loader/driverdisk.c:409 loader/driverdisk.c:441
#: loader/driverdisk.c:522 loader/driverselect.c:79 loader/driverselect.c:153
#: loader/driverselect.c:179 loader/hdinstall.c:212 loader/hdinstall.c:266
#: loader/kbd.c:119 loader/loader.c:510 loader/loader.c:527
#: loader/loader.c:1399 loader/loader.c:1432 loader/net.c:621
#: loader/net.c:1001 loader/net.c:1981 loader/net.c:2000
#: loader/nfsinstall.c:116 loader/urls.c:269
#: pyanaconda/storage/__init__.py:123 pyanaconda/storage/__init__.py:169
#: pyanaconda/storage/devicetree.py:90 pyanaconda/textw/constants_text.py:52
msgid "Back"
msgstr ""

#: loader/cdinstall.c:506
msgid "Cannot find kickstart file on CDROM."
msgstr ""

#: loader/copy.c:51 loader/method.c:287
#, c-format
msgid "Failed to read directory %s: %m"
msgstr ""

#: loader/driverdisk.c:274
msgid "Loading"
msgstr ""

#: loader/driverdisk.c:274
msgid "Reading driver disk"
msgstr ""

#: loader/driverdisk.c:403 loader/driverdisk.c:436
msgid "Driver Disk Source"
msgstr ""

#: loader/driverdisk.c:404
msgid ""
"You have multiple devices which could serve as sources for a driver disk.  "
"Which would you like to use?"
msgstr ""

#: loader/driverdisk.c:437
msgid ""
"There are multiple partitions on this device which could contain the driver "
"disk image.  Which would you like to use?"
msgstr ""

#: loader/driverdisk.c:472
msgid "Failed to mount partition."
msgstr ""

#: loader/driverdisk.c:477
msgid "Select driver disk image"
msgstr ""

#: loader/driverdisk.c:478
msgid "Select the file which is your driver disk image."
msgstr ""

#: loader/driverdisk.c:507
msgid "Failed to load driver disk from file."
msgstr ""

#: loader/driverdisk.c:519
#, c-format
msgid "Insert your driver disk into /dev/%s and press \"OK\" to continue."
msgstr ""

#: loader/driverdisk.c:522
msgid "Insert Driver Disk"
msgstr ""

#: loader/driverdisk.c:535
msgid "Failed to mount driver disk."
msgstr ""

#: loader/driverdisk.c:543
#, c-format
msgid "Driver disk is invalid for this release of %s."
msgstr ""

#: loader/driverdisk.c:609
msgid "Manually choose"
msgstr ""

#: loader/driverdisk.c:610
msgid "Load another disk"
msgstr ""

#: loader/driverdisk.c:611
msgid ""
"No devices of the appropriate type were found on this driver disk.  Would "
"you like to manually select the driver, continue anyway, or load another "
"driver disk?"
msgstr ""

#: loader/driverdisk.c:649
msgid "Driver disk"
msgstr ""

#: loader/driverdisk.c:650
msgid "Do you have a driver disk?"
msgstr ""

#: loader/driverdisk.c:659
msgid "More Driver Disks?"
msgstr ""

#: loader/driverdisk.c:660
msgid "Do you wish to load any more driver disks?"
msgstr ""

#: loader/driverdisk.c:709 loader/driverdisk.c:748 loader/hdinstall.c:360
#: loader/kickstart.c:135 loader/kickstart.c:145 loader/kickstart.c:187
#: loader/kickstart.c:192 loader/kickstart.c:339 loader/kickstart.c:355
#: loader/kickstart.c:571 loader/net.c:1654 loader/net.c:1675
#: loader/nfsinstall.c:414 loader/urlinstall.c:374 loader/urlinstall.c:385
#: loader/urlinstall.c:392
msgid "Kickstart Error"
msgstr ""

#: loader/driverdisk.c:710
#, c-format
msgid "Unknown driver disk kickstart source: %s"
msgstr ""

#: loader/driverdisk.c:749
#, c-format
msgid ""
"The following invalid argument was specified for the kickstart driver disk "
"command: %s"
msgstr ""

#: loader/driverselect.c:68
#, c-format
msgid ""
"Please enter any parameters which you wish to pass to the %s module "
"separated by spaces.  If you don't know what parameters to supply, skip this "
"screen by pressing the \"OK\" button."
msgstr ""

#: loader/driverselect.c:89
msgid "Enter Module Parameters"
msgstr ""

#: loader/driverselect.c:152
msgid "No drivers found"
msgstr ""

#: loader/driverselect.c:152
msgid "Load driver disk"
msgstr ""

#: loader/driverselect.c:153
msgid ""
"No drivers were found to manually insert.  Would you like to use a driver "
"disk?"
msgstr ""

#: loader/driverselect.c:171
msgid ""
"Please select the driver below which you wish to load.  If it does not "
"appear and you have a driver disk, press F2."
msgstr ""

#: loader/driverselect.c:180
msgid "Specify optional module arguments"
msgstr ""

#: loader/driverselect.c:205
msgid "Select Device Driver to Load"
msgstr ""

#: loader/hdinstall.c:116
msgid ""
"An error occured finding the installation image on your hard drive.  Please "
"check your images and try again."
msgstr ""

#: loader/hdinstall.c:213
msgid ""
"You don't seem to have any hard drives on your system! Would you like to "
"configure additional devices?"
msgstr ""

#: loader/hdinstall.c:226
#, c-format
msgid ""
"What partition and directory on that partition holds the installation image "
"for %s?  If you don't see the disk drive you're using listed here, press F2 "
"to configure additional devices."
msgstr ""

#: loader/hdinstall.c:250
msgid "Directory holding image:"
msgstr ""

#: loader/hdinstall.c:278
msgid "Select Partition"
msgstr ""

#: loader/hdinstall.c:326
#, c-format
msgid "Device %s does not appear to contain an installation image."
msgstr ""

#: loader/hdinstall.c:361
#, c-format
msgid "Bad argument to HD kickstart method command: %s"
msgstr ""

#: loader/hdinstall.c:441 loader/hdinstall.c:497
msgid "Cannot find kickstart file on hard drive."
msgstr ""

#: loader/hdinstall.c:484
#, c-format
msgid "Cannot find hard drive for BIOS disk %s"
msgstr ""

#: loader/kbd.c:117
msgid "Keyboard Type"
msgstr ""

#: loader/kbd.c:118
msgid "What type of keyboard do you have?"
msgstr ""

#: loader/kickstart.c:136
#, fuzzy, c-format
msgid "Error opening kickstart file %s: %m"
msgstr "خطا په پردازش %%ksappend lines: %s"

#: loader/kickstart.c:146
#, c-format
msgid "Error reading contents of kickstart file %s: %m"
msgstr ""

#: loader/kickstart.c:188
#, c-format
msgid "Error in %s on line %d of kickstart file %s."
msgstr ""

#: loader/kickstart.c:193
#, c-format
msgid "Missing options on line %d of kickstart file %s."
msgstr ""

#: loader/kickstart.c:300
msgid "Cannot find ks.cfg on removable media."
msgstr ""

#: loader/kickstart.c:340
#, c-format
msgid "Bad argument to device kickstart method command: %s"
msgstr ""

#: loader/kickstart.c:356
msgid "A module name must be specified for the kickstart device command."
msgstr ""

#: loader/kickstart.c:387
msgid ""
"Unable to download the kickstart file.  Please modify the kickstart "
"parameter below or press Cancel to proceed as an interactive installation."
msgstr ""

#: loader/kickstart.c:396
msgid "Error downloading kickstart file"
msgstr ""

#: loader/kickstart.c:572
#, c-format
msgid "Bad argument to shutdown kickstart method command: %s"
msgstr ""

#: loader/lang.c:63 loader/loader.c:227
#, c-format
msgid "Welcome to %s for %s"
msgstr ""

#: loader/lang.c:64
#, c-format
msgid "Welcome to %s for %s - Rescue Mode"
msgstr ""

#: loader/lang.c:65 loader/loader.c:251
msgid ""
"  <Tab>/<Alt-Tab> between elements  | <Space> selects | <F12> next screen "
msgstr ""

#: loader/lang.c:370
msgid "Choose a Language"
msgstr ""

#: loader/loader.c:131
msgid "Local CD/DVD"
msgstr ""

#: loader/loader.c:132
msgid "Hard drive"
msgstr ""

#: loader/loader.c:133
msgid "NFS directory"
msgstr ""

#: loader/loader.c:464 loader/loader.c:505
msgid "Update Disk Source"
msgstr ""

#: loader/loader.c:465
msgid ""
"You have multiple devices which could serve as sources for an update disk.  "
"Which would you like to use?"
msgstr ""

#: loader/loader.c:506
msgid ""
"There are multiple partitions on this device which could contain the update "
"disk image.  Which would you like to use?"
msgstr ""

#: loader/loader.c:524
#, c-format
msgid "Insert your updates disk into %s and press \"OK\" to continue."
msgstr ""

#: loader/loader.c:527
msgid "Updates Disk"
msgstr ""

#: loader/loader.c:545
msgid "Failed to mount updates disk"
msgstr ""

#: loader/loader.c:550
msgid "Updates"
msgstr ""

#: loader/loader.c:550
msgid "Reading anaconda updates"
msgstr ""

#: loader/loader.c:586
msgid ""
"Unable to download the updates image.  Please modify the updates location "
"below or press Cancel to proceed without updates.."
msgstr ""

#: loader/loader.c:595
msgid "Error downloading updates image"
msgstr ""

#: loader/loader.c:1196
#, c-format
msgid "You do not have enough RAM to install %s on this machine."
msgstr ""

#: loader/loader.c:1197
#, fuzzy, c-format
msgid ""
"You do not have enough RAM to install %s on this machine using this install "
"method."
msgstr ""
"شما را رم لازم په استفاده چه نصب کنوک گرافیکی نیست. حالت متنی شروع بیگنت."

#: loader/loader.c:1262
msgid "Media Detected"
msgstr ""

#: loader/loader.c:1263
msgid "Found local installation media"
msgstr ""

#: loader/loader.c:1391
msgid "Rescue Method"
msgstr ""

#: loader/loader.c:1392
msgid "Installation Method"
msgstr ""

#: loader/loader.c:1394
msgid "What type of media contains the rescue image?"
msgstr ""

#: loader/loader.c:1396
msgid "What type of media contains the installation image?"
msgstr ""

#: loader/loader.c:1431
msgid "No driver found"
msgstr ""

#: loader/loader.c:1431
msgid "Select driver"
msgstr ""

#: loader/loader.c:1432
msgid "Use a driver disk"
msgstr ""

#: loader/loader.c:1433
msgid ""
"Unable to find any devices of the type needed for this installation type.  "
"Would you like to manually select your driver or use a driver disk?"
msgstr ""

#: loader/loader.c:1664
msgid "The following devices have been found on your system."
msgstr ""

#: loader/loader.c:1666
msgid ""
"No device drivers have been loaded for your system.  Would you like to load "
"any now?"
msgstr ""

#: loader/loader.c:1670
msgid "Devices"
msgstr ""

#: loader/loader.c:1671
msgid "Done"
msgstr ""

#: loader/loader.c:1672
msgid "Add Device"
msgstr ""

#: loader/loader.c:1977
#, c-format
msgid "loader has already been run.  Starting shell.\n"
msgstr ""

#: loader/loader.c:2121
#, c-format
msgid "Driver disc was detected in %s. Do you want to use it?."
msgstr ""

#: loader/loader.c:2124
msgid "Driver disc detected"
msgstr ""

#: loader/loader.c:2124
msgid "Use it"
msgstr ""

#: loader/loader.c:2124
msgid "Skip it"
msgstr ""

#: loader/loader.c:2459
#, c-format
msgid "Running anaconda %s, the %s rescue mode - please wait.\n"
msgstr ""

#: loader/loader.c:2461
#, c-format
msgid "Running anaconda %s, the %s system installer - please wait.\n"
msgstr ""

#: loader/mediacheck.c:47
#, c-format
msgid "Unable to find install image %s"
msgstr ""

#: loader/mediacheck.c:53
#, c-format
msgid "Checking \"%s\"."
msgstr ""

#: loader/mediacheck.c:55
#, c-format
msgid "Checking media."
msgstr ""

#: loader/mediacheck.c:87
msgid ""
"Unable to find the checksum in the image.  This probably means the disc was "
"created without adding the checksum."
msgstr ""

#: loader/mediacheck.c:94
msgid "Unable to open the image."
msgstr ""

#: loader/mediacheck.c:98
msgid ""
"The image which was just tested has errors. This could be due to a corrupt "
"download or a bad disc.  If applicable, please clean the disc and try "
"again.  If this test continues to fail you should not continue the install."
msgstr ""

#: loader/mediacheck.c:106
msgid "Success"
msgstr ""

#: loader/mediacheck.c:107
msgid ""
"The image which was just tested was successfully verified.  It should be OK "
"to install from this media.  Note that not all media/drive errors can be "
"detected by the media check."
msgstr ""

#: loader/method.c:330
#, c-format
msgid ""
"Would you like to perform a checksum test of the ISO image:\n"
"\n"
"   %s?"
msgstr ""

#: loader/method.c:333
msgid "Checksum Test"
msgstr ""

#: loader/net.c:110
msgid "Invalid Prefix"
msgstr ""

#: loader/net.c:111
msgid ""
"Prefix must be between 1 and 32 for IPv4 networks or between 1 and 128 for "
"IPv6 networks"
msgstr ""

#: loader/net.c:506 loader/net.c:514 loader/net.c:569
#, c-format
msgid "There was an error configuring your network interface."
msgstr ""

#: loader/net.c:508
#, c-format
msgid ""
"\n"
"This cannot be corrected in cmdline mode.\n"
"Halting.\n"
msgstr ""

#: loader/net.c:513 loader/net.c:568 pyanaconda/textw/netconfig_text.py:403
msgid "Network Error"
msgstr ""

#: loader/net.c:599
msgid "Enable IPv4 support"
msgstr ""

#: loader/net.c:613
msgid "Enable IPv6 support"
msgstr ""

#: loader/net.c:653
msgid "Configure TCP/IP"
msgstr ""

#: loader/net.c:710
msgid "Missing Protocol"
msgstr ""

#: loader/net.c:711
msgid "You must select at least one protocol (IPv4 or IPv6)."
msgstr ""

#: loader/net.c:718
msgid "IPv4 Needed for NFS"
msgstr ""

#: loader/net.c:719
msgid "NFS installation method requires IPv4 support."
msgstr ""

#: loader/net.c:827
msgid "IPv4 address:"
msgstr ""

#: loader/net.c:839 loader/net.c:906 data/ui/netconfig.glade.h:1
msgid "/"
msgstr ""

#: loader/net.c:894
msgid "IPv6 address:"
msgstr ""

#: loader/net.c:960 pyanaconda/textw/netconfig_text.py:184
#: pyanaconda/textw/netconfig_text.py:224
msgid "Gateway:"
msgstr ""

#: loader/net.c:968
msgid "Name Server:"
msgstr ""

#: loader/net.c:1007
msgid ""
"Enter the IPv4 and/or the IPv6 address and prefix (address / prefix).  For "
"IPv4, the dotted-quad netmask or the CIDR-style prefix are acceptable. The "
"gateway and name server fields must be valid IPv4 or IPv6 addresses."
msgstr ""

#: loader/net.c:1024
msgid "Manual TCP/IP Configuration"
msgstr ""

#: loader/net.c:1148 loader/net.c:1156
msgid "Missing Information"
msgstr ""

#: loader/net.c:1149
msgid ""
"You must enter both a valid IPv4 address and a network mask or CIDR prefix."
msgstr ""

#: loader/net.c:1157
msgid "You must enter both a valid IPv6 address and a CIDR prefix."
msgstr ""

#: loader/net.c:1655
#, c-format
msgid "Bad argument to kickstart network command: %s"
msgstr ""

#: loader/net.c:1676
#, c-format
msgid "Bad bootproto %s specified in network command"
msgstr ""

#: loader/net.c:1781
msgid "Seconds:"
msgstr ""

#: loader/net.c:1976
msgid "Networking Device"
msgstr ""

#: loader/net.c:1977
msgid ""
"You have multiple network devices on this system. Which would you like to "
"install through?"
msgstr ""

#: loader/net.c:1981
msgid "Identify"
msgstr ""

#: loader/net.c:1990
msgid "You can identify the physical port for"
msgstr ""

#: loader/net.c:1992
msgid ""
"by flashing the LED lights for a number of seconds.  Enter a number between "
"1 and 30 to set the duration to flash the LED port lights."
msgstr ""

#: loader/net.c:1999
msgid "Identify NIC"
msgstr ""

#: loader/net.c:2012
#, fuzzy
msgid "Invalid Duration"
msgstr "دستی تنظیم گنگ"

#: loader/net.c:2013
msgid "You must enter the number of seconds as an integer between 1 and 30."
msgstr ""

#: loader/net.c:2025
#, c-format
msgid "Flashing %s port lights for %d seconds."
msgstr ""

#: loader/net.c:2195 loader/net.c:2199
#, c-format
msgid "Waiting for NetworkManager to configure %s.\n"
msgstr ""

#: loader/nfsinstall.c:93
msgid "NFS server name:"
msgstr ""

#: loader/nfsinstall.c:97
#, c-format
msgid "%s directory:"
msgstr ""

#: loader/nfsinstall.c:101
msgid "NFS mount options (optional):"
msgstr ""

#: loader/nfsinstall.c:107
#, c-format
msgid ""
"Please enter the server and path to your %s installation image and "
"optionally additional NFS mount options."
msgstr ""

#: loader/nfsinstall.c:115
msgid "NFS Setup"
msgstr ""

#: loader/nfsinstall.c:310
msgid "That directory could not be mounted from the server."
msgstr ""

#: loader/nfsinstall.c:322
#, c-format
msgid "That directory does not seem to contain a %s installation image."
msgstr ""

#: loader/nfsinstall.c:415
#, c-format
msgid "Bad argument to NFS kickstart method command: %s"
msgstr ""

#: loader/urlinstall.c:138
#, c-format
msgid "Unable to retrieve %s."
msgstr ""

#: loader/urlinstall.c:222
msgid "Unable to retrieve the install image."
msgstr ""

#: loader/urlinstall.c:375
#, c-format
msgid "Bad argument to URL kickstart method command: %s"
msgstr ""

#: loader/urlinstall.c:386
msgid "Must supply a --url argument to Url kickstart method."
msgstr ""

#: loader/urlinstall.c:393
#, c-format
msgid "Unknown Url method %s"
msgstr ""

#: loader/urls.c:178 loader/urls.c:186
msgid "Retrieving"
msgstr ""

#: loader/urls.c:272
#, c-format
msgid ""
"Please enter the URL containing the %s installation image on your server."
msgstr ""

#: loader/urls.c:290
msgid "Enable HTTP proxy"
msgstr ""

#: loader/urls.c:304
msgid "Proxy URL"
msgstr ""

#: loader/urls.c:309
msgid "Username"
msgstr ""

#: loader/urls.c:314
msgid "Password"
msgstr ""

#: loader/urls.c:333
msgid "URL Setup"
msgstr ""

#: loader/urls.c:341
msgid "You must enter a URL."
msgstr ""

#: loader/urls.c:347
msgid "URL must be either an ftp or http URL"
msgstr ""

#: loader/urls.c:356
msgid "Proxy must be either an ftp or http URL"
msgstr ""

#: loader/windows.c:66
msgid "Loading SCSI driver"
msgstr ""

#: loader/windows.c:67
#, c-format
msgid "Loading %s driver"
msgstr ""

#: pyanaconda/storage/__init__.py:110
msgid "Unknown Device"
msgstr ""

#: pyanaconda/storage/__init__.py:111
#, python-format
msgid ""
"The installation source given by device %s could not be found.  Please check "
"your parameters and try again."
msgstr ""

#: pyanaconda/storage/__init__.py:120
msgid "No disks found"
msgstr ""

#: pyanaconda/storage/__init__.py:121
msgid "No usable disks have been found."
msgstr ""

#: pyanaconda/storage/__init__.py:132
msgid "Installation cannot continue."
msgstr ""

#: pyanaconda/storage/__init__.py:133
msgid ""
"The storage configuration you have chosen has already been activated. You "
"can no longer return to the disk editing screen. Would you like to continue "
"with the installation process?"
msgstr ""

#: pyanaconda/storage/__init__.py:161
#, fuzzy
msgid "Encrypt device?"
msgstr "کلیت کد گنگ"

#: pyanaconda/storage/__init__.py:162
msgid ""
"You specified block device encryption should be enabled, but you have not "
"supplied a passphrase. If you do not go back and provide a passphrase, block "
"device encryption will be disabled."
msgstr ""

#: pyanaconda/storage/__init__.py:188 pyanaconda/storage/devicetree.py:99
msgid "Confirm"
msgstr ""

#: pyanaconda/storage/__init__.py:189
msgid ""
"The partitioning options you have selected will now be written to disk.  Any "
"data on deleted or reformatted partitions will be lost."
msgstr ""

#: pyanaconda/storage/__init__.py:194
msgid "Go _Back"
msgstr ""

#: pyanaconda/storage/__init__.py:195
msgid "_Write Changes to Disk"
msgstr ""

#: pyanaconda/storage/__init__.py:214
msgid "Running..."
msgstr ""

#: pyanaconda/storage/__init__.py:215
msgid "Storing encryption keys"
msgstr ""

#: pyanaconda/storage/__init__.py:231
#, python-format
msgid "Error storing an encryption key: %s\n"
msgstr ""

#: pyanaconda/storage/__init__.py:377
msgid "Examining Devices"
msgstr ""

#: pyanaconda/storage/__init__.py:378
msgid "Examining storage devices"
msgstr ""

#: pyanaconda/storage/__init__.py:657
msgid "This partition is holding the data for the hard drive install."
msgstr ""

#: pyanaconda/storage/__init__.py:662
msgid "You cannot delete a partition of a LDL formatted DASD."
msgstr ""

#: pyanaconda/storage/__init__.py:668
#, python-format
msgid "This device is part of the RAID device %s."
msgstr ""

#: pyanaconda/storage/__init__.py:671
msgid "This device is part of a RAID device."
msgstr ""

#: pyanaconda/storage/__init__.py:676
#, python-format
msgid "This device is part of the LVM volume group '%s'."
msgstr ""

#: pyanaconda/storage/__init__.py:679
msgid "This device is part of a LVM volume group."
msgstr ""

#: pyanaconda/storage/__init__.py:695
msgid ""
"This device is an extended partition which contains logical partitions that "
"cannot be deleted:\n"
"\n"
msgstr ""

#: pyanaconda/storage/__init__.py:970
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr ""

#: pyanaconda/storage/__init__.py:975
#, python-format
msgid ""
"Your root partition is less than 250 megabytes which is usually too small to "
"install %s."
msgstr ""

#: pyanaconda/storage/__init__.py:981
#, python-format
msgid ""
"Your / partition is less than %(min)s MB which is lower than recommended for "
"a normal %(productName)s install."
msgstr ""

#: pyanaconda/storage/__init__.py:991
#, python-format
msgid ""
"Your / partition does not match the the live image you are installing from.  "
"It must be formatted as %s."
msgstr ""

#: pyanaconda/storage/__init__.py:998
#, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s megabytes which is lower than "
"recommended for a normal %(productName)s install."
msgstr ""

#: pyanaconda/storage/__init__.py:1027
msgid ""
"Installing on a USB device.  This may or may not produce a working system."
msgstr ""

#: pyanaconda/storage/__init__.py:1030
msgid ""
"Installing on a FireWire device.  This may or may not produce a working "
"system."
msgstr ""

#: pyanaconda/storage/__init__.py:1037
msgid ""
"You have not specified a swap partition.  Due to the amount of memory "
"present, a swap partition is required to complete installation."
msgstr ""

#: pyanaconda/storage/__init__.py:1042
msgid ""
"You have not specified a swap partition.  Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""

#: pyanaconda/storage/__init__.py:1049
#, python-format
msgid ""
"This mount point is invalid.  The %s directory must be on the / file system."
msgstr ""

#: pyanaconda/storage/__init__.py:1053
#, python-format
msgid "The mount point %s must be on a linux file system."
msgstr ""

#: pyanaconda/storage/__init__.py:1064
msgid "No Drives Found"
msgstr ""

#: pyanaconda/storage/__init__.py:1065
msgid ""
"An error has occurred - no valid devices were found on which to create new "
"file systems. Please check your hardware for the cause of this problem."
msgstr ""

#: pyanaconda/storage/__init__.py:1363 pyanaconda/storage/__init__.py:1372
msgid "Dirty File Systems"
msgstr ""

#: pyanaconda/storage/__init__.py:1364
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Please boot your Linux installation, let the file systems be "
"checked and shut down cleanly to upgrade.\n"
"%s"
msgstr ""

#: pyanaconda/storage/__init__.py:1373
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Would you like to mount them anyway?\n"
"%s"
msgstr ""

#: pyanaconda/storage/__init__.py:1850
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"is an old-style Linux swap partition.  If you want to use this device for "
"swap space, you must reformat as a new-style Linux swap partition."
msgstr ""

#: pyanaconda/storage/__init__.py:1861
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. To perform an upgrade, please shut "
"down your system rather than hibernating it."
msgstr ""

#: pyanaconda/storage/__init__.py:1869
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. If you are performing a new install, "
"make sure the installer is set to format all swap devices."
msgstr ""

#: pyanaconda/storage/__init__.py:1881
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"does not contain a supported swap volume.  In order to continue "
"installation, you will need to format the device or skip it."
msgstr ""

#: pyanaconda/storage/__init__.py:1892
#, fuzzy, python-format
msgid ""
"Error enabling swap device %(name)s: %(msg)s\n"
"\n"
"The /etc/fstab on your upgrade partition does not reference a valid swap "
"device.\n"
"\n"
"Press OK to exit the installer"
msgstr ""
"نه تونیت ابزار اورش %s په %s کار بریت.\n"
"\n"
"هوبن آ بجنیت تا چه نصب کنوک در بیت"

#: pyanaconda/storage/__init__.py:1899
#, fuzzy, python-format
msgid ""
"Error enabling swap device %(name)s: %(msg)s\n"
"\n"
"This most likely means this swap device has not been initialized.\n"
"\n"
"Press OK to exit the installer."
msgstr ""
"نه تونیت ابزار اورش %s په %s کار بریت.\n"
"\n"
"هوبن آ بجنیت تا چه نصب کنوک در بیت"

#: pyanaconda/storage/__init__.py:1962 pyanaconda/storage/__init__.py:1974
msgid "Invalid mount point"
msgstr ""

#: pyanaconda/storage/__init__.py:1963
#, python-format
msgid ""
"An error occurred when trying to create %s.  Some element of this path is "
"not a directory. This is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""

#: pyanaconda/storage/__init__.py:1975
#, fuzzy, python-format
msgid ""
"An error occurred when trying to create %(mountpoint)s: %(msg)s.  This is a "
"fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"نه تونیت ابزار اورش %s په %s کار بریت.\n"
"\n"
"هوبن آ بجنیت تا چه نصب کنوک در بیت"

#: pyanaconda/storage/__init__.py:1991 pyanaconda/storage/__init__.py:2015
msgid "Unable to mount filesystem"
msgstr ""

#: pyanaconda/storage/__init__.py:1992
#, python-format
msgid ""
"An error occurred mounting device %(path)s as %(mountpoint)s.  You may "
"continue installation, but there may be problems."
msgstr ""

#: pyanaconda/storage/__init__.py:2016
#, fuzzy, python-format
msgid ""
"An error occurred mounting device %(path)s as %(mountpoint)s: %(msg)s. This "
"is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"نه تونیت ابزار اورش %s په %s کار بریت.\n"
"\n"
"هوبن آ بجنیت تا چه نصب کنوک در بیت"

#: pyanaconda/storage/dasd.py:155
msgid "Formatting DASD Device"
msgid_plural "Formatting DASD Devices"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/storage/dasd.py:156
#, python-format
msgid "Preparing %d DASD device for use with Linux..."
msgid_plural "Preparing %d DASD devices for use with Linux..."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/storage/devicelibs/lvm.py:312
#, python-format
msgid "vginfo failed for %s"
msgstr ""

#: pyanaconda/storage/devicelibs/lvm.py:341
#, python-format
msgid "lvs failed for %s"
msgstr ""

#: pyanaconda/storage/devices.py:1300 pyanaconda/storage/devices.py:1998
#: pyanaconda/storage/devices.py:2414 pyanaconda/storage/devices.py:2909
#: pyanaconda/storage/devices.py:3383
msgid "Creating"
msgstr ""

#: pyanaconda/storage/devices.py:1301 pyanaconda/storage/devices.py:1999
#: pyanaconda/storage/devices.py:2415 pyanaconda/storage/devices.py:2910
#, python-format
msgid "Creating device %s"
msgstr ""

#: pyanaconda/storage/devices.py:2508
#, python-format
msgid "A RAID%d set requires at least %d member"
msgid_plural "A RAID%d set requires at least %d members"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/storage/devices.py:3384
#, python-format
msgid "Creating file %s"
msgstr ""

#: pyanaconda/storage/devicetree.py:100
#, python-format
msgid ""
"Are you sure you want to skip entering a passphrase for device %s?\n"
"\n"
"If you skip this step the device's contents will not be available during "
"installation."
msgstr ""

#: pyanaconda/storage/devicetree.py:1897
msgid "This partition is part of an inconsistent LVM Volume Group."
msgstr ""

#: pyanaconda/storage/fcoe.py:66 pyanaconda/storage/fcoe.py:67
msgid "Connecting to FCoE SAN"
msgstr ""

#: pyanaconda/storage/fcoe.py:111
msgid "FCoE not available"
msgstr ""

#: pyanaconda/storage/formats/fs.py:102
msgid "filesystem configuration missing a type"
msgstr ""

#: pyanaconda/storage/formats/fs.py:354 pyanaconda/storage/formats/luks.py:194
#: pyanaconda/storage/formats/lvmpv.py:103
#: pyanaconda/storage/formats/swap.py:161
msgid "Formatting"
msgstr ""

#: pyanaconda/storage/formats/fs.py:355
#, python-format
msgid "Creating %s filesystem on %s"
msgstr ""

#: pyanaconda/storage/formats/fs.py:463
msgid "Resizing"
msgstr ""

#: pyanaconda/storage/formats/fs.py:464
#, python-format
msgid "Resizing filesystem on %s"
msgstr ""

#: pyanaconda/storage/formats/fs.py:499
#, python-format
msgid "Unknown return code: %d."
msgstr ""

#: pyanaconda/storage/formats/fs.py:513
msgid "Checking"
msgstr ""

#: pyanaconda/storage/formats/fs.py:514
#, python-format
msgid "Checking filesystem on %s"
msgstr ""

#: pyanaconda/storage/formats/fs.py:531
#, python-format
msgid "%(type)s filesystem check failure on %(device)s: "
msgstr ""

#: pyanaconda/storage/formats/fs.py:537
msgid ""
"Errors like this usually mean there is a problem with the filesystem that "
"will require user interaction to repair.  Before restarting installation, "
"reboot to rescue mode or another system that allows you to repair the "
"filesystem interactively.  Restart installation after you have corrected the "
"problems on the filesystem."
msgstr ""

#: pyanaconda/storage/formats/fs.py:545 pyanaconda/storage/partitioning.py:282
msgid "Unrecoverable Error"
msgstr ""

#: pyanaconda/storage/formats/fs.py:889
msgid "File system errors left uncorrected."
msgstr ""

#: pyanaconda/storage/formats/fs.py:890
msgid "Operational error."
msgstr ""

#: pyanaconda/storage/formats/fs.py:891
msgid "Usage or syntax error."
msgstr ""

#: pyanaconda/storage/formats/fs.py:892
msgid "e2fsck cancelled by user request."
msgstr ""

#: pyanaconda/storage/formats/fs.py:893
msgid "Shared library error."
msgstr ""

#: pyanaconda/storage/formats/fs.py:1052
msgid ""
"Recoverable errors have been detected or dosfsck has discovered an internal "
"inconsistency."
msgstr ""

#: pyanaconda/storage/formats/fs.py:1054
msgid "Usage error."
msgstr ""

#: pyanaconda/storage/formats/luks.py:48
#, fuzzy
msgid "Encrypted"
msgstr "کلیت کد گنگ"

#: pyanaconda/storage/formats/luks.py:195
#, python-format
msgid "Encrypting %s"
msgstr ""

#: pyanaconda/storage/formats/lvmpv.py:104
#: pyanaconda/storage/formats/swap.py:162
#, python-format
msgid "Creating %s on %s"
msgstr ""

#: pyanaconda/storage/iscsi.py:83 pyanaconda/storage/iscsi.py:84
msgid "Scanning iSCSI nodes"
msgstr ""

#: pyanaconda/storage/iscsi.py:135
msgid "Unable to change iSCSI initiator name once set"
msgstr ""

#: pyanaconda/storage/iscsi.py:137
msgid "Must provide an iSCSI initiator name"
msgstr ""

#: pyanaconda/storage/iscsi.py:177 pyanaconda/storage/iscsi.py:178
msgid "Initializing iSCSI initiator"
msgstr ""

#: pyanaconda/storage/iscsi.py:214
msgid "iSCSI not available"
msgstr ""

#: pyanaconda/storage/iscsi.py:216
msgid "No initiator name set"
msgstr ""

#: pyanaconda/storage/iscsi.py:230
msgid "No iSCSI nodes discovered"
msgstr ""

#: pyanaconda/storage/iscsi.py:233 pyanaconda/storage/iscsi.py:234
msgid "Logging in to iSCSI nodes"
msgstr ""

#: pyanaconda/storage/iscsi.py:260
msgid "No new iSCSI nodes discovered"
msgstr ""

#: pyanaconda/storage/iscsi.py:263
msgid "Could not log in to any of the discovered nodes"
msgstr ""

#: pyanaconda/storage/partitioning.py:197
msgid ""
"Could not find enough free space for automatic partitioning.  Press 'OK' to "
"exit the installer."
msgstr ""

#: pyanaconda/storage/partitioning.py:200
msgid ""
"Could not find enough free space for automatic partitioning, please use "
"another partitioning method."
msgstr ""

#: pyanaconda/storage/partitioning.py:229
msgid "Warnings During Automatic Partitioning"
msgstr "هوژاریانی وهد پارتیشن کنگ اتوماتیکی"

#: pyanaconda/storage/partitioning.py:231
#, python-format
msgid ""
"Following warnings occurred during automatic partitioning:\n"
"\n"
"%s"
msgstr ""
"جهلیگین هوژاریانی وهد اتوماتیکی پارتیشن کنگ پیش آتکنت: \n"
" \n"
"%s"

#: pyanaconda/storage/partitioning.py:245
#: pyanaconda/storage/partitioning.py:266
msgid ""
"\n"
"\n"
"Press 'OK' to exit the installer."
msgstr ""

#: pyanaconda/storage/partitioning.py:247
#, python-format
msgid ""
"Could not allocate requested partitions: \n"
"\n"
"%(msg)s.%(extra)s"
msgstr ""

#: pyanaconda/storage/partitioning.py:268
msgid ""
"\n"
"\n"
"Press 'OK' to choose a different partitioning option."
msgstr ""

#: pyanaconda/storage/partitioning.py:270
msgid "Automatic Partitioning Errors"
msgstr "خطایاں اتوماتیکین پارتیشن گنگ"

#: pyanaconda/storage/partitioning.py:271
#, python-format
msgid ""
"The following errors occurred with your partitioning:\n"
"\n"
"%(errortxt)s\n"
"\n"
"This can happen if there is not enough space on your hard drive(s) for the "
"installation. %(extra)s"
msgstr ""

#: pyanaconda/storage/zfcp.py:51
msgid "You have not specified a device number or the number is invalid"
msgstr ""

#: pyanaconda/storage/zfcp.py:53
msgid "You have not specified a worldwide port name or the name is invalid."
msgstr ""

#: pyanaconda/storage/zfcp.py:55
msgid "You have not specified a FCP LUN or the number is invalid."
msgstr ""

#: pyanaconda/storage/zfcp.py:133
#, python-format
msgid "zFCP device %s not found, not even in device ignore list."
msgstr ""

#: pyanaconda/storage/zfcp.py:143
#, python-format
msgid "Could not set zFCP device %(devnum)s online (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:154
#, python-format
msgid "Could not add WWPN %(wwpn)s to zFCP device %(devnum)s (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:161
#, python-format
msgid "WWPN %(wwpn)s not found at zFCP device %(devnum)s."
msgstr ""

#: pyanaconda/storage/zfcp.py:176
#, python-format
msgid ""
"Could not add LUN %(fcplun)s to WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:182
#, python-format
msgid ""
"LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s already configured."
msgstr ""

#: pyanaconda/storage/zfcp.py:194
#, python-format
msgid ""
"Could not read failed attribute of LUN %(fcplun)s at WWPN %(wwpn)s on zFCP "
"device %(devnum)s (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:203
#, python-format
msgid ""
"Failed LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s removed "
"again."
msgstr ""

#: pyanaconda/storage/zfcp.py:260
#, python-format
msgid ""
"Could not correctly delete SCSI device of zFCP %(devnum)s %(wwpn)s "
"%(fcplun)s (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:269
#, python-format
msgid ""
"Could not remove LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:287
#, python-format
msgid "Could not remove WWPN %(wwpn)s on zFCP device %(devnum)s (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:313
#, python-format
msgid "Could not set zFCP device %(devnum)s offline (%(e)s)."
msgstr ""

#: pyanaconda/textw/complete_text.py:32
msgid "Reboot"
msgstr ""

#: pyanaconda/textw/complete_text.py:34
msgid "<Enter> to exit"
msgstr ""

#: pyanaconda/textw/complete_text.py:62
msgid "Complete"
msgstr ""

#: pyanaconda/textw/keyboard_text.py:48
msgid "Keyboard Selection"
msgstr ""

#: pyanaconda/textw/keyboard_text.py:49
msgid "Which model keyboard is attached to this computer?"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:43
#, python-format
msgid "A value is required for the field %s"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:126
#: pyanaconda/textw/netconfig_text.py:152 data/ui/netconfig.glade.h:9
msgid "Enable network interface"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:129
msgid ""
"This requires that you have an active network connection during the "
"installation process.  Please select network interface to configure."
msgstr ""

#: pyanaconda/textw/netconfig_text.py:155
#, python-format
msgid "Configure interface %s to be used during installation process."
msgstr ""

#: pyanaconda/textw/netconfig_text.py:160
msgid "Enable IPv4 Support"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:167
#: pyanaconda/textw/netconfig_text.py:207
#, fuzzy
msgid "Manual Configuration"
msgstr "دستی تنظیم گنگ"

#: pyanaconda/textw/netconfig_text.py:175
msgid "IPv4 Address:"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:189
#: pyanaconda/textw/netconfig_text.py:229
msgid "Nameserver:"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:197
msgid "Enable IPv6 Support"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:204
#, fuzzy
msgid "Dynamic IP Configuration (DHCPv6)"
msgstr "ـ داینامیکی آی ‍پی کارمز کنت(DHCP) "

#: pyanaconda/textw/netconfig_text.py:215
msgid "IPv6 Address:"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:270
msgid "Missing protocol"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:271
msgid "You must select at least one protocol version"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:279
#: pyanaconda/textw/netconfig_text.py:282
msgid "IPv4 Address"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:286
#: pyanaconda/textw/netconfig_text.py:291
msgid "IPv4 Prefix"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:298
msgid "IPv4 Gateway"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:307
msgid "IPv4 Nameserver"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:315
#: pyanaconda/textw/netconfig_text.py:318
msgid "IPv6 Address"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:322
#: pyanaconda/textw/netconfig_text.py:327
msgid "IPv6 Prefix"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:326
msgid "IPv6 CIDR prefix must be between 0 and 128."
msgstr ""

#: pyanaconda/textw/netconfig_text.py:334
msgid "IPv6 Gateway"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:342
msgid "IPv6 Nameserver"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:399
msgid "Configuring Network Interfaces"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:404
#, python-format
msgid "There was an error configuring network device %s"
msgstr ""

#: pyanaconda/textw/partition_text.py:59
msgid "Partitioning Type"
msgstr ""

#: pyanaconda/textw/partition_text.py:61
msgid ""
"Installation requires partitioning of your hard drive.  The default layout "
"is suitable for most users.  Select what space to use and which drives to "
"use as the install target."
msgstr ""

#: pyanaconda/textw/partition_text.py:64
msgid "Use entire drive"
msgstr ""

#: pyanaconda/textw/partition_text.py:65
msgid "Replace existing Linux system"
msgstr ""

#: pyanaconda/textw/partition_text.py:66
msgid "Use free space"
msgstr ""

#: pyanaconda/textw/partition_text.py:81
msgid "Which drive(s) do you want to use for this installation?"
msgstr ""

#: pyanaconda/textw/partition_text.py:96
msgid "<Space>,<+>,<-> selection   |   <F2> Add drive   |   <F12> next screen"
msgstr ""

#: pyanaconda/textw/progress_text.py:46
msgid "Package Installation"
msgstr ""

#: pyanaconda/textw/timezone_text.py:74
msgid "In which time zone are you located?"
msgstr ""

#: pyanaconda/textw/timezone_text.py:92
msgid "System clock uses UTC"
msgstr ""

#: pyanaconda/textw/upgrade_bootloader_text.py:111
#: pyanaconda/textw/upgrade_bootloader_text.py:121
msgid "Update boot loader configuration"
msgstr ""

#: pyanaconda/textw/upgrade_bootloader_text.py:124
msgid "Skip boot loader updating"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:125
msgid "Free Space"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:143
msgid "RAM detected (MB):"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:146
msgid "Suggested size (MB):"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:149
msgid "Swap file size (MB):"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:157
msgid "Add Swap"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:182
msgid "The value you entered is not a valid number."
msgstr ""

#: pyanaconda/textw/upgrade_text.py:214
msgid "Reinstall System"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:226
msgid "System to Upgrade"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:227
msgid ""
"There seem to be one or more existing Linux installations on your system.\n"
"\n"
"Please choose one to upgrade, or select 'Reinstall System' to freshly "
"install your system."
msgstr ""

#: pyanaconda/textw/userauth_text.py:30
msgid "Root Password"
msgstr ""

#: pyanaconda/textw/userauth_text.py:33
msgid ""
"Pick a root password. You must type it twice to ensure you know it and do "
"not make a typing mistake. "
msgstr ""

#: pyanaconda/textw/userauth_text.py:67
msgid "The root password must be at least 6 characters long."
msgstr ""

#: pyanaconda/textw/userauth_text.py:84
#, python-format
msgid ""
"You have provided a weak password: %s\n"
"\n"
"Would you like to continue with this password?"
msgstr ""

#: pyanaconda/textw/welcome_text.py:29
#, python-format
msgid "%s"
msgstr ""

#: pyanaconda/textw/welcome_text.py:30
#, python-format
msgid ""
"Welcome to %s!\n"
"\n"
msgstr ""

#: pyanaconda/textw/zipl_text.py:36
msgid ""
"The z/IPL Boot Loader will be installed on your system after installation is "
"complete. You can now enter any additional kernel and chandev parameters "
"which your machine or your setup require."
msgstr ""

#: pyanaconda/textw/zipl_text.py:68
msgid "z/IPL Configuration"
msgstr ""

#: pyanaconda/textw/zipl_text.py:76 pyanaconda/textw/zipl_text.py:80
msgid "Chandev line "
msgstr ""

#: data/liveinst/liveinst.desktop.in.h:1
#, fuzzy
msgid "Install"
msgstr "دست بروگا تنظیم کتن"

#: data/liveinst/liveinst.desktop.in.h:2
msgid "Install the live CD to your hard disk"
msgstr ""

#: data/liveinst/liveinst.desktop.in.h:3
msgid "Install to Hard Drive"
msgstr ""

#: liveinst:5
#, fuzzy
msgid "Starting Install to Hard Drive"
msgstr "گرافیکی نصب شروع بیگنت..."

#: data/ui/GroupSelector.glade.h:1
msgid ""
"Some packages associated with this group are not required to be installed "
"but may provide additional functionality.  Please choose the packages which "
"you would like to have installed."
msgstr ""

#: data/ui/GroupSelector.glade.h:2
msgid "_Deselect"
msgstr ""

#: data/ui/GroupSelector.glade.h:3
msgid "_Deselect all optional packages"
msgstr ""

#: data/ui/GroupSelector.glade.h:4
msgid "_Optional packages"
msgstr ""

#: data/ui/GroupSelector.glade.h:5
msgid "_Select"
msgstr ""

#: data/ui/GroupSelector.glade.h:6
msgid "_Select all optional packages"
msgstr ""

#: data/ui/GroupSelector.glade.h:7
msgid "dialog1"
msgstr ""

#: data/ui/account.glade.h:1
msgid "Confirm:"
msgstr ""

#: data/ui/account.glade.h:2
msgid "Root Password:"
msgstr ""

#: data/ui/account.glade.h:3
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""

#: data/ui/adddrive.glade.h:1
msgid "Add _FCoE SAN"
msgstr ""

#: data/ui/adddrive.glade.h:2
msgid "Add _ZFCP LUN"
msgstr ""

#: data/ui/adddrive.glade.h:3
msgid "Add _iSCSI target"
msgstr ""

#: data/ui/adddrive.glade.h:4
msgid "Advanced Storage Options"
msgstr ""

#: data/ui/adddrive.glade.h:5
msgid "How would you like to modify your drive configuration?"
msgstr ""

#: data/ui/adddrive.glade.h:6
msgid "_Add drive"
msgstr ""

#: data/ui/addrepo.glade.h:1
msgid "<b>Repository _name:</b>"
msgstr ""

#: data/ui/addrepo.glade.h:2
msgid "<b>Repository _type:</b>"
msgstr ""

#: data/ui/addrepo.glade.h:4
msgid "Configure _proxy"
msgstr ""

#: data/ui/addrepo.glade.h:5
msgid ""
"HTTP/FTP\n"
"CD/DVD\n"
"NFS\n"
"Hard Drive"
msgstr ""

#: data/ui/addrepo.glade.h:9
msgid ""
"Please provide the configuration information for this software repository."
msgstr ""

#: data/ui/addrepo.glade.h:10
msgid "Proxy U_RL (host:port)"
msgstr ""

#: data/ui/addrepo.glade.h:11
msgid "Proxy pass_word"
msgstr ""

#: data/ui/addrepo.glade.h:12
msgid "Proxy u_sername"
msgstr ""

#: data/ui/addrepo.glade.h:13
msgid "Repository _URL"
msgstr ""

#: data/ui/addrepo.glade.h:14
msgid "Select A Directory"
msgstr ""

#: data/ui/addrepo.glade.h:15
msgid "URL is a _mirror list"
msgstr ""

#: data/ui/addrepo.glade.h:16
msgid "_Directory"
msgstr ""

#: data/ui/addrepo.glade.h:17
msgid "_Options"
msgstr ""

#: data/ui/addrepo.glade.h:18
msgid "_Partition"
msgstr ""

#: data/ui/addrepo.glade.h:19
msgid "_Path"
msgstr ""

#: data/ui/addrepo.glade.h:20
msgid "_Server"
msgstr ""

#: data/ui/anaconda.glade.h:1
msgid "Reboo_t"
msgstr ""

#: data/ui/anaconda.glade.h:4
msgid "_Next"
msgstr ""

#: data/ui/autopart.glade.h:1
msgid "<b>Shrink partition _to size (in MB):</b>"
msgstr ""

#: data/ui/autopart.glade.h:2
msgid "Re_view and modify partitioning layout"
msgstr ""

#: data/ui/autopart.glade.h:3
msgid "Volume to Shrink"
msgstr ""

#: data/ui/autopart.glade.h:4
msgid ""
"Which partition would you like to shrink to make room for your installation?"
msgstr ""

#: data/ui/autopart.glade.h:5
msgid "Which type of installation would you like?"
msgstr ""

#: data/ui/autopart.glade.h:6
msgid "_Encrypt system"
msgstr ""

#: data/ui/autopart.glade.h:7
msgid "_Shrink"
msgstr ""

#: data/ui/blwhere.glade.h:1
msgid "/boot"
msgstr ""

#: data/ui/blwhere.glade.h:2
msgid "BIOS Drive Order"
msgstr ""

#: data/ui/blwhere.glade.h:3
msgid "Boot loader device"
msgstr ""

#: data/ui/blwhere.glade.h:4
msgid "First BIOS drive:"
msgstr ""

#: data/ui/blwhere.glade.h:5
msgid "Fourth BIOS drive:"
msgstr ""

#: data/ui/blwhere.glade.h:6
msgid "MBR"
msgstr ""

#: data/ui/blwhere.glade.h:7
msgid "Second BIOS drive:"
msgstr ""

#: data/ui/blwhere.glade.h:8
msgid "Third BIOS drive:"
msgstr ""

#: data/ui/blwhere.glade.h:9
msgid "Where would you like to install the boot loader for your system?"
msgstr ""

#: data/ui/cleardisks.glade.h:1
msgid "<b>Data Storage Devices</b> (to be mounted only)"
msgstr ""

#: data/ui/cleardisks.glade.h:2
msgid "<b>Install Target Devices</b>"
msgstr ""

#: data/ui/cleardisks.glade.h:3
msgid ""
"<b>Tip:</b> Install target devices will be reformatted and wiped of any "
"data.  Make sure you have backups."
msgstr ""

#: data/ui/cleardisks.glade.h:4
msgid ""
"Below are the storage devices you've selected to be a part of this "
"installation.  Please indicate using the arrows below which devices you'd "
"like to use as data devices (these will not be formatted, only mounted) and "
"which devices you'd like to use as installation target devices (these may be "
"formatted).  Please also indicate which system drive will have the "
"bootloader installed."
msgstr ""

#: data/ui/create-storage.glade.h:1
msgid ""
"<span size=\"small\" color=\"gray\">Create a RAID formatted partition</span>"
msgstr ""

#: data/ui/create-storage.glade.h:2
msgid ""
"<span size=\"small\" color=\"gray\">Create a logical volume on selected "
"volume group</span>"
msgstr ""

#: data/ui/create-storage.glade.h:3
msgid ""
"<span size=\"small\" color=\"gray\">Create an LVM formatted partition</span>"
msgstr ""

#: data/ui/create-storage.glade.h:4
msgid ""
"<span size=\"small\" color=\"gray\">General purpose partition creation</span>"
msgstr ""

#: data/ui/create-storage.glade.h:5
msgid ""
"<span size=\"small\" color=\"gray\">Requires at least 1 free LVM formatted "
"partition</span>"
msgstr ""

#: data/ui/create-storage.glade.h:6
msgid ""
"<span size=\"small\" color=\"gray\">Requires at least 2 free RAID formatted "
"partitions</span>"
msgstr ""

#: data/ui/create-storage.glade.h:7
msgid "C_reate"
msgstr ""

#: data/ui/create-storage.glade.h:8
msgid "Create LVM"
msgstr ""

#: data/ui/create-storage.glade.h:9
msgid "Create Partition"
msgstr ""

#: data/ui/create-storage.glade.h:10
msgid "Create Software RAID"
msgstr ""

#: data/ui/create-storage.glade.h:11
msgid "Create Storage"
msgstr ""

#: data/ui/create-storage.glade.h:12
msgid "LVM Logical Volume"
msgstr ""

#: data/ui/create-storage.glade.h:13
msgid "LVM Physical Volume"
msgstr ""

#: data/ui/create-storage.glade.h:14
msgid "LVM Volume Group"
msgstr ""

#: data/ui/create-storage.glade.h:16
msgid "RAID Partition"
msgstr ""

#: data/ui/create-storage.glade.h:17
msgid "Standard Partition"
msgstr ""

#: data/ui/detailed-dialog.glade.h:1
msgid "Info"
msgstr ""

#: data/ui/detailed-dialog.glade.h:2
msgid "_Details"
msgstr ""

#: data/ui/fcoe-config.glade.h:1
msgid "Configure FCoE Parameters"
msgstr ""

#: data/ui/fcoe-config.glade.h:2
msgid "NIC:"
msgstr ""

#: data/ui/fcoe-config.glade.h:3
msgid ""
"Please select the network interface which is connected to\n"
"your FCoE switch."
msgstr ""

#: data/ui/fcoe-config.glade.h:5
msgid "Use DCB"
msgstr ""

#: data/ui/fcoe-config.glade.h:6
msgid "_Add FCoE Disk(s)"
msgstr ""

#: data/ui/filter.glade.h:1
msgid ""
"<b>Tip:</b> Selected drives will not be formatted unless you choose to do so "
"later during installation.  Also, note that post-installation you may mount "
"drives you did not select here by modifying your /etc/fstab file."
msgstr ""

#: data/ui/filter.glade.h:2
msgid "Add Advanced Target"
msgstr ""

#: data/ui/filter.glade.h:3
msgid "Basic Devices"
msgstr ""

#: data/ui/filter.glade.h:4
msgid "Filter By:"
msgstr ""

#: data/ui/filter.glade.h:5
msgid "Firmware RAID"
msgstr ""

#: data/ui/filter.glade.h:6
msgid "Identifier:"
msgstr ""

#: data/ui/filter.glade.h:7
msgid ""
"Interconnect\n"
"Vendor\n"
"Identifier"
msgstr ""

#: data/ui/filter.glade.h:10
msgid "LUN:"
msgstr ""

#: data/ui/filter.glade.h:11
msgid "Multipath Devices"
msgstr ""

#: data/ui/filter.glade.h:12
msgid "Other SAN Devices"
msgstr ""

#: data/ui/filter.glade.h:13
msgid ""
"Please select the drives you'd like to install the operating system on, as "
"well as any drives you'd like to automatically mount on your system:"
msgstr ""

#: data/ui/filter.glade.h:14
msgid ""
"Port / Target / LUN\n"
"Target Identifier"
msgstr ""

#: data/ui/filter.glade.h:16
msgid "Port:"
msgstr ""

#: data/ui/filter.glade.h:17
msgid "Search"
msgstr ""

#: data/ui/filter.glade.h:18
msgid "Search By:"
msgstr ""

#: data/ui/filter.glade.h:19
msgid "Search Results:"
msgstr ""

#: data/ui/filter.glade.h:21
#, no-c-format
msgid "Selected devices: %s (%s) out of %s (%s)."
msgstr ""

#: data/ui/filter.glade.h:22
msgid "Show Identifiers that Include:"
msgstr ""

#: data/ui/filter.glade.h:23
msgid "Show Only Devices From:"
msgstr ""

#: data/ui/filter.glade.h:24
msgid "Show Only Devices Using:"
msgstr ""

#: data/ui/filter.glade.h:25
msgid "Target:"
msgstr ""

#: data/ui/iscsi-config.glade.h:1
msgid "<b>CHAP _Password:</b>"
msgstr ""

#: data/ui/iscsi-config.glade.h:2
#, fuzzy
msgid "<b>CHAP _Username:</b>"
msgstr "FCP LUN"

#: data/ui/iscsi-config.glade.h:3
msgid "<b>Reverse CHAP P_assword:</b>"
msgstr ""

#: data/ui/iscsi-config.glade.h:4
msgid "<b>Reverse CHAP U_sername:</b>"
msgstr ""

#: data/ui/iscsi-config.glade.h:5
msgid "<b>_Target IP Address:</b>"
msgstr ""

#: data/ui/iscsi-config.glade.h:6
msgid "<b>iSCSI Initiator _Name:</b>"
msgstr ""

#: data/ui/iscsi-config.glade.h:7
msgid "Configure iSCSI Parameters"
msgstr ""

#: data/ui/iscsi-config.glade.h:8
msgid ""
"To use iSCSI disks, you must provide the address of your iSCSI target and "
"the iSCSI initiator name you've configured for your host."
msgstr ""

#: data/ui/iscsi-config.glade.h:9
msgid "_Add target"
msgstr ""

#: data/ui/lukspassphrase.glade.h:1
msgid ""
"Also add this passphrase to all existing encrypted devices to streamline the "
"boot process"
msgstr ""

#: data/ui/lukspassphrase.glade.h:2
msgid ""
"Choose a passphrase for this encrypted partition. You will be prompted for "
"the passphrase during system boot."
msgstr ""

#: data/ui/lukspassphrase.glade.h:3
msgid "Confirm passphrase:"
msgstr ""

#: data/ui/lukspassphrase.glade.h:4
msgid "Enter passphrase for encrypted partition"
msgstr ""

#: data/ui/lukspassphrase.glade.h:5
msgid "Enter passphrase:"
msgstr ""

#: data/ui/netconfig.glade.h:2
msgid "<b>Gateway:</b>"
msgstr ""

#: data/ui/netconfig.glade.h:3
msgid "<b>IPv4 Address:</b>"
msgstr ""

#: data/ui/netconfig.glade.h:4
msgid "<b>IPv6 Address:</b>"
msgstr ""

#: data/ui/netconfig.glade.h:5
msgid "<b>Nameserver:</b>"
msgstr ""

#: data/ui/netconfig.glade.h:6
msgid "<b>_Interface:</b>"
msgstr ""

#: data/ui/netconfig.glade.h:7
msgid "Enable IPv_4 support"
msgstr ""

#: data/ui/netconfig.glade.h:8
msgid "Enable IPv_6 support"
msgstr ""

#: data/ui/netconfig.glade.h:11
msgid "Use _dynamic IP configuration (DHCP)"
msgstr "ـ داینامیکی آی ‍پی کارمز کنت(DHCP) "

#: data/ui/network.glade.h:1
msgid "Configure Network"
msgstr ""

#: data/ui/network.glade.h:2
msgid "Hostname:"
msgstr ""

#: data/ui/network.glade.h:3
msgid ""
"Please name this computer.  The hostname identifies the computer on a "
"network."
msgstr ""

#: data/ui/tasksel.glade.h:1
msgid "Customize _later"
msgstr "بادن تغییرـ دهگ بیت"

#: data/ui/tasksel.glade.h:2
msgid ""
"Please select any additional repositories that you want to use for software "
"installation."
msgstr ""
"لطفا هر گیشین امبار شما که لوٹیت په نصب سافت ور ضرورت اینت انتحاب کنیت."

#: data/ui/tasksel.glade.h:4
#, no-c-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage.  What additional tasks would you like your system to "
"support?"
msgstr ""

#: data/ui/tasksel.glade.h:5
msgid ""
"You can further customize the software selection now, or after install via "
"the software management application."
msgstr ""
"شما تونت الان زورتگن سافت ور گیشتر بدل کنیت یاں بعد چه نصب بوگ از طریق "
"کارمرز مدیریت ساوفت ور ٹگلی بدهیت"

#: data/ui/tasksel.glade.h:6
msgid "_Add additional software repositories"
msgstr "ـدگه گیشین امبار سافت ور هور کن"

#: data/ui/tasksel.glade.h:7
msgid "_Customize now"
msgstr "ـالان بدلی کن"

#: data/ui/tasksel.glade.h:8
msgid "_Modify repository"
msgstr "ـتغییر دهگی انبار"

#: data/ui/zfcp-config.glade.h:1
msgid "<b>Device number:</b>"
msgstr "شماره دسگاه"

#: data/ui/zfcp-config.glade.h:2
msgid "<b>FCP LUN:</b>"
msgstr "FCP LUN"

#: data/ui/zfcp-config.glade.h:3
msgid "<b>WWPN:</b>"
msgstr "WWPN"

#: data/ui/zfcp-config.glade.h:4
msgid "Add FCP device"
msgstr "وسیله   FCP هور کنت"

#: data/ui/zfcp-config.glade.h:5
msgid ""
"zSeries machines can access industry-standard SCSI devices via Fibre Channel "
"(FCP). You need to provide a 16 bit device number, a 64 bit World Wide Port "
"Name (WWPN), and a 64 bit FCP LUN for each device."
msgstr ""

#: data/lang-table.h:1
msgid "Afrikaans"
msgstr "آپریکایی"

#: data/lang-table.h:2
msgid "Arabic"
msgstr "عربی"

#: data/lang-table.h:3
msgid "Assamese"
msgstr "اسامس"

#: data/lang-table.h:4
msgid "Bengali"
msgstr "بنگالی"

#: data/lang-table.h:5
msgid "Bengali(India)"
msgstr "بنگالی(هندی)"

#: data/lang-table.h:6
msgid "Bulgarian"
msgstr "بلغاری"

#: data/lang-table.h:7
msgid "Catalan"
msgstr "کاتالان"

#: data/lang-table.h:8
msgid "Chinese(Simplified)"
msgstr "چینی(ساده)"

#: data/lang-table.h:9
msgid "Chinese(Traditional)"
msgstr "چینی(سنتی)"

#: data/lang-table.h:10
msgid "Croatian"
msgstr "کرواتی"

#: data/lang-table.h:11
msgid "Czech"
msgstr "چک"

#: data/lang-table.h:12
msgid "Danish"
msgstr "دانیش"

#: data/lang-table.h:13
msgid "Dutch"
msgstr "داچ"

#: data/lang-table.h:14
msgid "English"
msgstr "انگریزی"

#: data/lang-table.h:15
msgid "Estonian"
msgstr "استونیایی"

#: data/lang-table.h:16
msgid "Finnish"
msgstr "فلاندی"

#: data/lang-table.h:17
msgid "French"
msgstr "فرانسه ای"

#: data/lang-table.h:18
msgid "German"
msgstr "جرمنی"

#: data/lang-table.h:19
msgid "Greek"
msgstr "یونانی"

#: data/lang-table.h:20
msgid "Gujarati"
msgstr "گجراتی"

#: data/lang-table.h:21
msgid "Hebrew"
msgstr ""

#: data/lang-table.h:22
msgid "Hindi"
msgstr "هندی"

#: data/lang-table.h:23
msgid "Hungarian"
msgstr "مجاری"

#: data/lang-table.h:24
msgid "Icelandic"
msgstr "ایس آیلندیک"

#: data/lang-table.h:25
msgid "Iloko"
msgstr "ایلوکو"

#: data/lang-table.h:26
msgid "Indonesian"
msgstr "اندونیزیایی"

#: data/lang-table.h:27
msgid "Italian"
msgstr "ایتالیایی"

#: data/lang-table.h:28
msgid "Japanese"
msgstr "ژاپنی"

#: data/lang-table.h:29
msgid "Kannada"
msgstr "کانادا"

#: data/lang-table.h:30
msgid "Korean"
msgstr "کوریایی"

#: data/lang-table.h:31
msgid "Macedonian"
msgstr "مقدونیایی"

#: data/lang-table.h:32
#, fuzzy
msgid "Maithili"
msgstr "ماراتی"

#: data/lang-table.h:33
msgid "Malay"
msgstr "مالایی"

#: data/lang-table.h:34
msgid "Malayalam"
msgstr "مالایامی"

#: data/lang-table.h:35
msgid "Marathi"
msgstr "ماراتی"

#: data/lang-table.h:36
#, fuzzy
msgid "Nepali"
msgstr "بنگالی"

#: data/lang-table.h:37
#, fuzzy
msgid "Norwegian(Bokmål)"
msgstr "نوروژی"

#: data/lang-table.h:38
msgid "Northern Sotho"
msgstr "سوتو شمالی"

#: data/lang-table.h:39
msgid "Oriya"
msgstr "اوریا"

#: data/lang-table.h:40
msgid "Persian"
msgstr "پارسی"

#: data/lang-table.h:41
msgid "Polish"
msgstr "لهستانی"

#: data/lang-table.h:42
msgid "Portuguese"
msgstr "پرتگیزی"

#: data/lang-table.h:43
msgid "Portuguese(Brazilian)"
msgstr "پرتگیزی( برزیلی)"

#: data/lang-table.h:44
msgid "Punjabi"
msgstr "پنجابی"

#: data/lang-table.h:45
msgid "Romanian"
msgstr "رومانیایی"

#: data/lang-table.h:46
msgid "Russian"
msgstr "روسی"

#: data/lang-table.h:47
msgid "Serbian"
msgstr "صربی"

#: data/lang-table.h:48
msgid "Serbian(Latin)"
msgstr "صربی لاتینی"

#: data/lang-table.h:49
msgid "Sinhala"
msgstr "سینهالا"

#: data/lang-table.h:50
msgid "Slovak"
msgstr "اوسلواکی"

#: data/lang-table.h:51
msgid "Slovenian"
msgstr "اسوانیایی"

#: data/lang-table.h:52
msgid "Spanish"
msgstr "اسپانیایی"

#: data/lang-table.h:53
msgid "Swedish"
msgstr "سوپدی"

#: data/lang-table.h:54
#, fuzzy
msgid "Tajik"
msgstr "تامیلی"

#: data/lang-table.h:55
msgid "Tamil"
msgstr "تامیلی"

#: data/lang-table.h:56
msgid "Telugu"
msgstr "تلوگو"

#: data/lang-table.h:57
msgid "Turkish"
msgstr "ترکی"

#: data/lang-table.h:58
msgid "Ukrainian"
msgstr "اوکراینی"

#: data/lang-table.h:59
msgid "Vietnamese"
msgstr "ویتنامی"

#: data/lang-table.h:60
msgid "Welsh"
msgstr "ولزی"

#: data/lang-table.h:61
msgid "Zulu"
msgstr "زولو"

#~ msgid ""
#~ "You do not have enough RAM to use the graphical installer.  Starting text "
#~ "mode."
#~ msgstr ""
#~ "شما را رم لازم په استفاده چه نصب کنوک گرافیکی نیست. حالت متنی شروع بیگنت."

#, fuzzy
#~ msgid "Starting graphical installation."
#~ msgstr "گرافیکی نصب شروع بیگنت..."

#~ msgid "Install class forcing text mode installation"
#~ msgstr "حالت متنی وصل بوگا کلاس فورسینگ وصل بکن"

#, fuzzy
#~ msgid ""
#~ "The following error was found while parsing thekickstart configuration "
#~ "file:\n"
#~ "\n"
#~ "%s"
#~ msgstr ""
#~ "جهلیگین خطا وهد وانگ پیداگ شمی تنظیمات kickstart :\n"
#~ "\n"
#~ "%s"

#, fuzzy
#~ msgid ""
#~ "An error was encountered while activating your storage configuration."
#~ msgstr ""
#~ "جهلیگین خطا وهد وانگ پیداگ شمی تنظیمات kickstart :\n"
#~ "\n"
#~ "%s"
